### ISSUE TITLE
Examples are out of date...

### ISSUE THREAD

**Issue by ajohnstone** [sparkleformation/sparkle_formation#100]
```
SparkleFormation.sparkle_path = File.join(File.dirname(__FILE__), '')
```

```
andrew@andrew-office:~/Desktop/projects/github/photobox/services-operations/aws/sparkleformation/cloudformation$ ./generate.rb templates/ec2-svcs-container-service.rb 
./generate.rb:9:in `block (3 levels) in templates': undefined method `sparkle_path=' for #<Class:0x00000001ac3180>::SparkleFormation (NoMethodError)
```

**Comment by chrisroberts** [comment]
Hi. The examples still work as expected. The `SparkleFormation.sparkle_path` attribute cannot be set from within a template (as it's required prior to the template being evaluated) nor does it have the proper scoping to access the attribute. From the looks of the error, it seems like this is how you're attempting to change it. 

Also, you might have an easier time using the sparkleformation CLI tool: https://github.com/sparkleformation/sfn

It even has a handy `print` command to output the generated results of the template. If you are still having issues, please feel free to re-open this issue. Cheers!
