### ISSUE TITLE
Stack policies usage

### ISSUE THREAD

**Issue by josqu4red** [sparkleformation/sparkle_formation#103]
Policies added on resources as shown in [doc](http://www.sparkleformation.io/docs/sparkle_formation/stack-policies.html) (template usage part) are rendered just like other statements in the final template.

For instance, this addition
```diff
diff --git a/vpc.rb b/vpc.rb
index e08aebf..0c0963b 100644
--- a/vpc.rb
+++ b/vpc.rb
@@ -52,6 +52,9 @@ SparkleFormation.new(
       vpc_id ref!(:vpc)
       tags tag_list!("pub-rtb")
     end
+    policy do
+      deny '*'
+    end
   end

   resources(:public_default_route) do
```

gives
```
[Sfn]: Modified Resources:
  - PublicRouteTable [AWS::EC2::RouteTable]
    Policy:
      : (none) -> {"Deny"=>"*"}
```

using `sfn diff` and update obviously fails with `ValidationError: Invalid template resource property 'Policy'`.

Could you help sorting this out ?
Thanks in advance.

**Comment by chrisroberts** [comment]
Hi! The stack policy support is provided via a callback so it must be enabled within your configuration file:

* http://www.sparkleformation.io/docs/sfn/callbacks.html#builtin-callbacks

Please feel free to re-open this issue if you still encounter problems. Cheers!

**Comment by josqu4red** [comment]
Oh I didn't notice this. You should probably mention it in the Stack policy documentation.

Thanks for the quick answer !
