### ISSUE TITLE
undefined method `[]' for nil:NilClass on sfn update

### ISSUE THREAD

**Issue by Typositoire** [sparkleformation/sparkle_formation#135]
```ruby
heartbeat =
  [
    {
      :VolumesFrom => [],
      :PortMappings => [],
      :Command => [],
      :Environment => [
        {
          :Name => "port",
          :Value => "5053"
        },
        {
          :Name => "XXXX",
          :Value => "XXXX"
        },
        {
          :Name => "XXXX",
          :Value => "XXXX"
        }
      ],
      :Essential => true,
      :EntryPoint => [],
      :Links => [],
      :MountPoints => [],
      :Memory => 256,
      :Cpu => 10,
      :Image => "XXXX:7",
      :Name => "XXXX"
    }
  ]

  dynamic!(:ecs_task_definition, :XXXXX) do
    properties do
      container_definitions heartbeat
      volumes []
    end
  end
```

I have a template containing the above code. Modifying anything in heartbeat array makes any `sfn update` return the error `undefined method ```[]' for nil:NilClass`

I can modify anything else (dynamics, registry etc...), and the `sfn update` works.

Any idea?

**Comment by chrisroberts** [comment]
toss a `DEBUG=true` in and paste in the stacktrace:

```
$ DEBUG=true sfn update ...
```

Thanks!

**Comment by Typositoire** [comment]
```bash
⇒  DEBUG=true sfn update utilities-development -f sparkleformation/templates/utilities/development.rb -d #yolo
[Sfn]: SparkleFormation: update
[Sfn]:   -> Name: utilities-development Path: /Users/yanndavid/development/devtools/sparkle-formation/sfn-provision_devtools/sparkleformation/templates/utilities/development.rb
[Sfn]: Stack runtime parameters:
ERROR: NoMethodError: undefined method `[]' for nil:NilClass
/Users/yanndavid/.rvm/gems/ruby-2.2.1/gems/sfn-1.2.0/lib/sfn/planner/aws.rb:339:in `register_diff'
/Users/yanndavid/.rvm/gems/ruby-2.2.1/gems/sfn-1.2.0/lib/sfn/planner/aws.rb:304:in `block in run_stack_diff'
/Users/yanndavid/.rvm/gems/ruby-2.2.1/gems/sfn-1.2.0/lib/sfn/planner/aws.rb:303:in `each'
/Users/yanndavid/.rvm/gems/ruby-2.2.1/gems/sfn-1.2.0/lib/sfn/planner/aws.rb:303:in `run_stack_diff'
/Users/yanndavid/.rvm/gems/ruby-2.2.1/gems/sfn-1.2.0/lib/sfn/planner/aws.rb:192:in `plan_stack'
/Users/yanndavid/.rvm/gems/ruby-2.2.1/gems/sfn-1.2.0/lib/sfn/planner/aws.rb:134:in `generate_plan'
/Users/yanndavid/.rvm/gems/ruby-2.2.1/gems/sfn-1.2.0/lib/sfn/command/update.rb:94:in `execute!'
/Users/yanndavid/.rvm/gems/ruby-2.2.1/gems/sfn-1.2.0/bin/sfn:40:in `block (4 levels) in <top (required)>'
/Users/yanndavid/.rvm/gems/ruby-2.2.1/gems/bogo-cli-0.1.32/lib/bogo-cli/setup.rb:26:in `call'
/Users/yanndavid/.rvm/gems/ruby-2.2.1/gems/bogo-cli-0.1.32/lib/bogo-cli/setup.rb:26:in `block in bogo_cli_run'
/Users/yanndavid/.rvm/gems/ruby-2.2.1/gems/slop-3.6.0/lib/slop.rb:260:in `call'
/Users/yanndavid/.rvm/gems/ruby-2.2.1/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
/Users/yanndavid/.rvm/gems/ruby-2.2.1/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
/Users/yanndavid/.rvm/gems/ruby-2.2.1/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
/Users/yanndavid/.rvm/gems/ruby-2.2.1/gems/slop-3.6.0/lib/slop.rb:54:in `parse'
/Users/yanndavid/.rvm/gems/ruby-2.2.1/gems/bogo-cli-0.1.32/lib/bogo-cli/setup.rb:48:in `define'
/Users/yanndavid/.rvm/gems/ruby-2.2.1/gems/sfn-1.2.0/bin/sfn:6:in `<top (required)>'
/Users/yanndavid/.rvm/gems/ruby-2.2.1/bin/sfn:23:in `load'
/Users/yanndavid/.rvm/gems/ruby-2.2.1/bin/sfn:23:in `<main>'
/Users/yanndavid/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/Users/yanndavid/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

Side note, doing a sfn create --print-only and using the generate json in cloud-formation directly to do the update works.

**Comment by chrisroberts** [comment]
Great, thanks! Let me generate a failing spec based on what you have and i'll get an update pushed out. You can also work around the issue with sfn directly by disabling the planner:

```
$ sfn update --no-plan STACK_NAME --file TEMPLATE
```

Thanks!

**Comment by Typositoire** [comment]
15 minutes from issue to fix/work around. You're awesome!

**Comment by chrisroberts** [comment]
Hi, the latest sfn release had some updates applied to the planner that should have fixed this issue. If you are still experiencing problems, please let me know. Thanks!

**Comment by Typositoire** [comment]
Thanks! I got some update done using the new version and everything worked!

**Comment by KeerthigaKrishnan** [comment]
Hi, 

When I perform sfn create, I am getting this error 
ATH017069:sparkleformation kkrishnan$ sfn create testazure --debug --file compute.rb 
/Users/kkrishnan/.rvm/gems/ruby-2.4.0/gems/sparkle_formation-3.0.20/lib/sparkle_formation/sparkle.rb:114: warning: constant ::Fixnum is deprecated
/Users/kkrishnan/.rvm/gems/ruby-2.4.0/gems/sparkle_formation-3.0.20/lib/sparkle_formation/sparkle.rb:114: warning: constant ::Bignum is deprecated
/Users/kkrishnan/.rvm/gems/ruby-2.4.0/gems/sparkle_formation-3.0.20/lib/sparkle_formation/sparkle.rb:114: warning: constant ::NIL is deprecated
/Users/kkrishnan/.rvm/gems/ruby-2.4.0/gems/sparkle_formation-3.0.20/lib/sparkle_formation/sparkle.rb:114: warning: constant ::TRUE is deprecated
/Users/kkrishnan/.rvm/gems/ruby-2.4.0/gems/sparkle_formation-3.0.20/lib/sparkle_formation/sparkle.rb:114: warning: constant ::FALSE is deprecated
[DEBUG]: Initial compile parameters - {}
[DEBUG]: Merged compile parameters - {}
[Sfn]: SparkleFormation: create
[Sfn]:   -> Name: testazure
[Sfn]: Stack runtime parameters: - template: testazure
[Sfn]: sparkle Image Id [14.04.2-LTS]: 
[Sfn]: sparkle Flavor: f
[ERROR]: Not an allowed value: Standard_D1
[Sfn]: sparkle Flavor: Standard_D1
[Sfn]: storage Account Name: keerthiazu
[Sfn]: storage Container Name: keertiaz
[Sfn]: Events for Stack: testazure
I, [2017-04-13T15:25:26.338121 #54703]  INFO -- : Lock aquired for stack update. Requesting stacks from upstream. (#<Thread:0x007f939b87c8d8>)
I, [2017-04-13T15:25:27.073883 #54703]  INFO -- : Stack list has been updated from upstream and cached locally
Time                      Resource Logical Id        Resource Status      Resource Status Reason   
2017-04-13 09:55:26 UTC   sparkleNetworkInterfaces   Failed               BadRequest               
ERROR: NoMethodError: undefined method `map' for nil:NilClass
/Users/kkrishnan/.rvm/gems/ruby-2.4.0/gems/sfn-3.0.22/lib/sfn/command/events.rb:80:in `block in get_events'
/Users/kkrishnan/.rvm/gems/ruby-2.4.0/gems/sfn-3.0.22/lib/sfn/command/events.rb:65:in `map'
/Users/kkrishnan/.rvm/gems/ruby-2.4.0/gems/sfn-3.0.22/lib/sfn/command/events.rb:65:in `get_events'
/Users/kkrishnan/.rvm/gems/ruby-2.4.0/gems/bogo-ui-0.1.24/lib/bogo-ui/table.rb:35:in `method_missing'
/Users/kkrishnan/.rvm/gems/ruby-2.4.0/gems/sfn-3.0.22/lib/sfn/command/events.rb:24:in `block (3 levels) in execute!'
/Users/kkrishnan/.rvm/gems/ruby-2.4.0/gems/bogo-ui-0.1.24/lib/bogo-ui/table.rb:56:in `table'
/Users/kkrishnan/.rvm/gems/ruby-2.4.0/gems/sfn-3.0.22/lib/sfn/command/events.rb:23:in `block (2 levels) in execute!'
/Users/kkrishnan/.rvm/gems/ruby-2.4.0/gems/bogo-ui-0.1.24/lib/bogo-ui/table.rb:78:in `instance_exec'
/Users/kkrishnan/.rvm/gems/ruby-2.4.0/gems/bogo-ui-0.1.24/lib/bogo-ui/table.rb:78:in `display'
/Users/kkrishnan/.rvm/gems/ruby-2.4.0/gems/sfn-3.0.22/lib/sfn/command/events.rb:49:in `block in execute!'
/Users/kkrishnan/.rvm/gems/ruby-2.4.0/gems/sfn-3.0.22/lib/sfn/command_module/callbacks.rb:19:in `api_action!'
/Users/kkrishnan/.rvm/gems/ruby-2.4.0/gems/sfn-3.0.22/lib/sfn/command/events.rb:21:in `execute!'
/Users/kkrishnan/.rvm/gems/ruby-2.4.0/gems/sfn-3.0.22/lib/sfn/command_module/base.rb:129:in `poll_stack'
/Users/kkrishnan/.rvm/gems/ruby-2.4.0/gems/sfn-3.0.22/lib/sfn/command/create.rb:66:in `block in execute!'
/Users/kkrishnan/.rvm/gems/ruby-2.4.0/gems/sfn-3.0.22/lib/sfn/command_module/callbacks.rb:19:in `api_action!'
/Users/kkrishnan/.rvm/gems/ruby-2.4.0/gems/sfn-3.0.22/lib/sfn/command/create.rb:63:in `execute!'
/Users/kkrishnan/.rvm/gems/ruby-2.4.0/gems/sfn-3.0.22/bin/sfn:52:in `block (4 levels) in <top (required)>'
/Users/kkrishnan/.rvm/gems/ruby-2.4.0/gems/bogo-cli-0.2.12/lib/bogo-cli/setup.rb:26:in `block in bogo_cli_run'
/Users/kkrishnan/.rvm/gems/ruby-2.4.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
/Users/kkrishnan/.rvm/gems/ruby-2.4.0/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
/Users/kkrishnan/.rvm/gems/ruby-2.4.0/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
/Users/kkrishnan/.rvm/gems/ruby-2.4.0/gems/slop-3.6.0/lib/slop.rb:54:in `parse'
/Users/kkrishnan/.rvm/gems/ruby-2.4.0/gems/bogo-cli-0.2.12/lib/bogo-cli/setup.rb:48:in `define'
/Users/kkrishnan/.rvm/gems/ruby-2.4.0/gems/sfn-3.0.22/bin/sfn:14:in `<top (required)>'
/Users/kkrishnan/.rvm/gems/ruby-2.4.0/bin/sfn:22:in `load'
/Users/kkrishnan/.rvm/gems/ruby-2.4.0/bin/sfn:22:in `<main>'
/Users/kkrishnan/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
/Users/kkrishnan/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'


ATH017069:sparkleformation kkrishnan$ ruby --version 
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
ATH017069:sparkleformation kkrishnan$ sfn --version
/Users/kkrishnan/.rvm/gems/ruby-2.4.0/gems/sparkle_formation-3.0.20/lib/sparkle_formation/sparkle.rb:114: warning: constant ::Fixnum is deprecated
/Users/kkrishnan/.rvm/gems/ruby-2.4.0/gems/sparkle_formation-3.0.20/lib/sparkle_formation/sparkle.rb:114: warning: constant ::Bignum is deprecated
/Users/kkrishnan/.rvm/gems/ruby-2.4.0/gems/sparkle_formation-3.0.20/lib/sparkle_formation/sparkle.rb:114: warning: constant ::NIL is deprecated
/Users/kkrishnan/.rvm/gems/ruby-2.4.0/gems/sparkle_formation-3.0.20/lib/sparkle_formation/sparkle.rb:114: warning: constant ::TRUE is deprecated
/Users/kkrishnan/.rvm/gems/ruby-2.4.0/gems/sparkle_formation-3.0.20/lib/sparkle_formation/sparkle.rb:114: warning: constant ::FALSE is deprecated
sfn - SparkleFormation CLI - [Version: 3.0.22]
ATH017069:sparkleformation kkrishnan$ 


Could someone help me with this?. I feel like we need to update the version

**Comment by chrisroberts** [comment]
It looks like the API behavior may have changed. To work around it for now, you can break this into two commands:

```
$ sfn create test-stack -f test-template --no-poll
$ sfn events test-stack
```

**Comment by KeerthigaKrishnan** [comment]
Yes, I am able to pass that.. Thank you so much.

**Comment by KeerthigaKrishnan** [comment]
Can I pass json file as a template to create vm in azure.. ?. Because, when I try , sfn was not able to recognize the file ..
