### ISSUE TITLE
Issue loading sparklepack

### ISSUE THREAD

**Issue by jimcroft** [sparkleformation/sparkle_formation#148]
Hi

I've created a sparklepack but am having problems adding it in a template.

The template looks like this the following (I added the STDERR lines to aid debugging):

```
require 'sparklepack-core'
core_pack = ::SparkleFormation::SparklePack.new(name: 'sparklepack-core')

sfn = SparkleFormation.new(:devstack) do
  # Stuff
end

STDERR.puts core_pack.inspect
STDERR.puts sfn.sparkle.inspect

sfn.sparkle.add_sparkle(core_pack)
```

The output when run is

```
$ sfn create DevstackTemplates-Testing --file devstack                                              
<SparkleFormation::Sparkle [root: "/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/bundler/gems/sparklepack-core-26acc19f2336/lib/sparkleformation"]>
<SparkleFormation::Sparkle [root: <SparkleFormation::Sparkle [root: "/Users/jim/dev/cfn/devstack/sparkleformation"]>]>
ERROR: NoMethodError: undefined method `name=' for #<SparkleFormation::SparkleCollection:0x007fb6940414b8>
```

Any idea why I'm getting NoMethodError when calling add_sparkle? I'm using Ruby 2.2.4, sparkle_formation 1.2.0 and sfn 1.2.0.

PS. I'm having to use ```::SparkleFormation::SparklePack``` rather than ```SparkleFormation::SparklePack``` to avoid getting this error:

```ERROR: NameError: uninitialized constant #<Class:0x007fc89c879080>::SparkleFormation::SparklePack```

Any pointers here would also be appreciated.

**Comment by chrisroberts** [comment]
Hi! You want to enable your pack within your `.sfn` configuration file:

```ruby
Configuration.new do
  sparkle_pack 'sparklepack-core'
```

When `sfn` creates the template instance it will load the defined sparklepacks into the template instance. You should not have to bother with packs directly within your template file. This repository can provide a pretty good example of a pack and has local usage information as well: https://github.com/carnivore-rb/sparkle-pack-jackal-cfn

Let me know if you have any troubles.

Cheers!

**Comment by jimcroft** [comment]
Thanks for the quick response. All good now. :+1:
