### ISSUE TITLE
Support for MFA on AWS

### ISSUE THREAD

**Issue by aabes** [sparkleformation/sparkle_formation#149]
Our IAM policies require MFA to be present. Sparkle formation seems to not like it, or more correctly, seems that sfn/miasma doesn't know how to use AWS_SECURITY_TOKEN in addition to access_key and secret key.

(as a side note, I'm using aws-mfa wrapper)

**Comment by chrisroberts** [comment]
Hi! You can set this in your `.sfn` configuration file:

```ruby
Configuration.new do
  credentials do
    provider :aws
    credentials do
      aws_sts_token ENV['AWS_SECURITY_TOKEN']
```

That should get you what you need. If you are still having problems, please let me know.

Cheers!

**Comment by aabes** [comment]
thanks for quick reply! but this doesn't quite cut it.
Seems that aws_sts_token is only used when:
          if(creds[:aws_sts_role_arn])
            sts_assume_role!(creds)
          end

In my case, using MFA requires user input to establish a new Access Key/Secret and a SECURITY_TOKEN. The 3 together are used to authenticate API requests.

**Comment by chrisroberts** [comment]
The `:aws_sts_token` will be used if it is provided. The code you pasted above relates to generating the new key/secret/token when the user is assuming a role. Please check that you are using the latest version of the miasma-aws library as there was a bug in previous versions that required re-auth with the STS service even when not required (like when the token is provided directly).

**Comment by aabes** [comment]
You, dear sir, are absolutely helpful and correct. 
an update fixed the issue.

**Comment by chrisroberts** [comment]
Fantastic! If you have any other issues, please let me know!
