### ISSUE TITLE
re-using dynamics & components

### ISSUE THREAD

**Issue by till** [sparkleformation/sparkle_formation#157]
Has anyone explored how to re-use dynamics? We are maintaining 8 or 10 stacks on AWS and I was wondering if e.g. the best way is to manage/maintain all those stacks from a single git repository, or if anyone had figured out how to create a library of "base" dynamics and components which I can require through bundler somehow?

**Comment by chrisroberts** [comment]
Hi! What you are describing are "SparklePacks". You can read more about them here:

http://www.sparkleformation.io/docs/sparkle_formation/sparkle-packs.html

And here are a couple example packs:

https://github.com/carnivore-rb/sparkle-pack-jackal-cfn
https://github.com/hw-labs/sparkle-pack-aws-amis

If you need more information or have any questions about them, please let me know. Cheers!

**Comment by till** [comment]
@chrisroberts apologies, and thanks!
