### ISSUE TITLE
Compile time parameters don't get instantiated when inheriting another template

### ISSUE THREAD

**Issue by rabidscorpio** [sparkleformation/sparkle_formation#159]
So I'm running into an issue where compile time parameters don't get instantiated when that stack inherits another stack. Here's what I mean:
```
require 'sparkle_formation'
require 'netaddr'
SparkleFormation.new('vpc', :inherit => 'base_vpc') do
  network = NetAddr::CIDR.create state!(:default_cidr_block)
end
```
```
require 'sparkle_formation'
SparkleFormation.new('base_vpc',
  :parameters => {
    :default_cidr_block => {
      :type               => :string,
      :description        => "Default network for this VPC.",
      :default            => "10.201.0.0/16",
      :prompt_when_nested => false,
    }
  }) do
  set!('AWSTemplateFormatVersion', '2010-09-09')
end
```
The above works. The following, however, does not:
```
require 'sparkle_formation'
require 'netaddr'
SparkleFormation.new('vpc',
  :inherit => 'base_vpc',
  :parameters => {
    :default_cidr_block => {
      :type               => :string,
      :description        => "Default network for this VPC.",
      :default            => "10.201.0.0/16",
      :prompt_when_nested => false,
    }
  }
) do
  network = NetAddr::CIDR.create state!(:default_cidr_block)
end
```
```
require 'sparkle_formation'
SparkleFormation.new('base_vpc') do
  set!('AWSTemplateFormatVersion', '2010-09-09')
end
```
With the latter, I get  ```ERROR: ArgumentError: String or Integer expected for argument 'addr' but NilClass provided.```

**Comment by chrisroberts** [comment]
Hi! I actually ran into this while refactoring the internal structure of template instances. The compile time parameters are getting overwritten where they should be getting merged. The update is here:

https://github.com/sparkleformation/sparkle_formation/commit/4b5fc8fd8d012ad00af36a63fd551260ec3810ae#diff-b026ffa80720942d68829a897e0b05fbL505

which is living in the `develop` branch and will be getting release shortly. Will close this once it's released. Thanks for reporting the issue!

**Comment by rabidscorpio** [comment]
Awesome, thanks @chrisroberts!

**Comment by chrisroberts** [comment]
Fixed and released. Thanks for the report!
