### ISSUE TITLE
In-line documentation for provider-specific helpers lacks usage details

### ISSUE THREAD

**Issue by cwjohnston** [sparkleformation/sparkle_formation#164]
The [helper methods](http://www.sparkleformation.io/docs/sparkle_formation/helper-methods.html) documentation links to YARDoc output for provider-specific helpers. The in-line documentation for these methods is pretty sparse, requiring one to delve into the source in order to understand which additional arguments a helper may take.

For example, per the YARDoc, AWS `_cf_join` helper accepts a rather opaque `args (Object)` argument. Only by reading the source for this helper method do we see that one of the args is an options hash where the delimiter can be specified.

**Comment by chrisroberts** [comment]
Added and published.
