### ISSUE TITLE
Big templates fail to upload to CloudFormation

### ISSUE THREAD

**Issue by devkid** [sparkleformation/sparkle_formation#166]
We are trying to create a kind of large stack (31 instances) and first ran into the following error:
```bash
ERROR: RuntimeError: entity expansion has grown too large
```

We circumvented the problem by prepending the following line to our SparkleFormation script:
```ruby
REXML::Security.entity_expansion_text_limit = 102400
```

However, the template still seems too large to be accepted by CloudFormation:
```bash
ERROR: Miasma::Error::ApiError::RequestError: Bad Request - ValidationError: 1 validation error detected: Value '{"Parameters": ... <large wall of text containing the generated template> }' at 'templateBody' failed to satisfy constraint: Member must have length less than or equal to 51200
```

There is an option `TemplateURL` for [`CreateStack`](http://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_CreateStack.html) which can use an S3 URL to fetch a template (restriction: 460,800 Bytes).

**Comment by chrisroberts** [comment]
Hi! This was an issue in the SparkleFormation CLI (`sfn`) and referenced in issue sparkleformation/sfn#179 and implemented via sparkleformation/sfn#184 which is available in the 3.0 release. Thanks!
