### ISSUE TITLE
AWS : Get region configured in .sfn ?

### ISSUE THREAD

**Issue by Esya** [sparkleformation/sparkle_formation#172]
Hi,

Is there a way to know from my template which region is currently setup in `.sfn` ? 
I created a registry that has all the availability zones, and I'd like to do something like this :  

```ruby
parameters(:first_az) do
  description "First Availability Zone"
  type 'AWS::EC2::AvailabilityZone::Name'
  default registry!(:azs, :region => region!)[0]
end

parameters(:second_az) do
  description "Second Availability Zone"
  type 'AWS::EC2::AvailabilityZone::Name'
  default registry!(:azs, :region => region!)[1]
end
```

But here `region!` is a reference to AWS::Region, not the actual region, and therefore it doesnt do the registry lookup. 

(Ps, I have a dirty workaround using system! but I'd like to avoid that!)
Thanks

**Comment by chrisroberts** [comment]
Hi! There is no way to access the `.sfn` configuration information from a template (in any direct way). Can you provide a bit more information on what you are trying to accomplish with the availability zones and the registry items? What you are attempting to do is definitely possible using conditionals which removes the need for having any contextual knowledge of the configuration contents, but if you can expand a bit on what you are trying to do, we might be able to break it down a bit more. 

Thanks!

**Comment by Esya** [comment]
Hi Chris,

What I want to do is to offer the first and second availability zone as default for those parameters depending on the region currently selected for the stack, so that if you're on us-west-1 it does :

```
[Sfn]: First Az [us-west-1a]:
[Sfn]: Second Az [us-west-1b]:
```

Right now I did this as a quick work around

```ruby
SfnRegistry.register(:azs) do
  region = system!("cat .sfn | grep 'aws_region' | cut -d \"'\" -f2 | tr -d '\n'")
  case region
  when 'us-west-1'
    ['us-west-1a','us-west-1b','us-west-1c']
  when 'us-west-2'
    ['us-west-2a','us-west-2b','us-west-2c']
  when 'us-east-1'
    ['us-east-1a','us-east-1b','us-east-1c','us-east-1d','us-east-1e']
... # Other regions here
  else
    ['','']
  end
end
```

**Comment by chrisroberts** [comment]
Okay, so if we setup the parameters with a known default value we can add a couple conditions to check if a custom value has been provided:

```ruby
parameters do
  first_az do
    type 'AWS::EC2::AvailabilityZone::Name'
    default 'unset'
  end
  second_az do
    type 'AWS::EC2::AvailabilityZone::Name'
    default 'unset'
  end
end
conditions do
  first_az_set not!(equals!(ref!(:first_az), 'unset'))
  second_az_set not!(equals!(ref!(:second_az), 'unset'))
end
```

now, with these you can use the intrinsic functions to accomplish the same thing:

```ruby
SfnRegistry.register(:first_az) do
  if!(:first_az_set, ref!(:first_az), select!(azs!, 0))
end
SfnRegistry.register(:second_az) do
  if!(:second_az_set, ref!(:second_az), select!(azs!, 1))
end
```

and using it would then look like:

```ruby
properties do
  availability_zone registry!(:first_az)
```

This also removes the hard coded values from the resultant template JSON which means you can move the template from region to region outside of sfn and get the desired result.

Let me know if that helps. Cheers!

**Comment by Esya** [comment]
Hi Chris,

Sorry to re-open this issue, this helps a lot for some things and thank you for that, but the issue is that we do need to do some things at compile time.

For example, we start a different amount of instances based on the region, and we cannot rely on the AWS::Region property for example.

What is your take on this? Is there a simple way to read the defined region value? For now we're relying on a hack which is not very pretty.

**Comment by luckymike** [comment]
@Esya this may help: https://github.com/hw-labs/sparkle-pack-aws-availability-zones it collects the available AZs at compile time. You can load that in your project, or adapt the registry code as needed.

**Comment by chrisroberts** [comment]
I would suggest using a mapping to provide those values for you, where the region dictates things like number of instances. As an example:

```ruby
SparkleFormation.new(:test) do
  mappings do
    set!('us-east-1'.disable_camel!) do
      number_of_instances 5
    end
    set!('us-west-2'.disable_camel!) do
      number_of_instances 2
    end
  end
  ...
  resources.my_asg do
    type 'AWS::AutoScaling::AutoScalingGroup'
    properties do
      ...
      max_size find_in_map!(region!, :number_of_instances)
      min_size find_in_map!(region!, :number_of_instances)
    end
  end
end
```

Does this kind of approach solve the problem you're running into?
