### ISSUE TITLE
Documentation: Why use sparkle formation over alternatives?

### ISSUE THREAD

**Issue by sammcj** [sparkleformation/sparkle_formation#175]
I stumbled across this on some HN comments recently and was wondering why you'd use Sparkle Formation over other existing tools.

Perhaps adding to the documentation a section on this might be helpful for people weighing up the various options.

At the moment I'm using [Terraform](https://github.com/hashicorp/terraform) as it's really widely used and I've found it to be rock solid, there's been the odd thing it doesn't do but so far it's made up for that in many other ways - it looks like Sparkle Formation seems to do some of what Terraform does but perhaps the differences could be clarified?

Thanks,

**Comment by chrisroberts** [comment]
That's great that terraform is working for you. SparkleFormation is focused on utilizing provider orchestration APIs via declarative templates, which is explicitly how it is different from terraform. 

Marking as task to toss in a simple comparison page to the docs with an explanation on how SparkleFormation works wrt templates and provider APIs.

**Comment by chrisroberts** [comment]
Closing this as TF support is just about integrated making this whole issue moot :)
