### ISSUE TITLE
How can I specify references in the `unique_string` function for Azure?

### ISSUE THREAD

**Issue by russellseymour** [sparkleformation/sparkle_formation#181]
Azure provides a way to generate a unique string for the storage account.  Sparkle has provision for this in the function `unique_string!`.

I need to be able to generate the following:

```
"storageAccountName": "[uniqueString(subscription().subscriptionId, resourceGroup().id]"
```

As can be seen the references are specific to Azure and are not strings.  However when I specify them in  Sparkle like this:

```
set!("storage_account_name", unique_string!("subscription().subscriptionId", "resourceGroup().id"))
```

I end up with:

```
"storageAccountName": "[uniqueString('subscription().subscriptionId', 'resourceGroup().id']"
```

Which now just attempt to generate a `unique_string` on the static strings rather than the values that these functions would return.

How can I specify these values to `unique_string` so that it parses the linting for Sparkle yet still give me the desired result in the ARM template?

Thanks, Russell

**Comment by chrisroberts** [comment]
Hi! You can get the desired results by using the helper methods as parameters and not providing strings. The example you gave above can be rewritten as:

```ruby
  storage_account_name unique_string!(subscription!.subscriptionId, resource_group!.id)
```

which will give you the desired result:

```json
"storageAccountName": "[uniqueString(subscription().subscriptionId, resourceGroup().id)]"
```

If you still end up with any issues, please just re-open this issue or create a new one.

Cheers!
