### ISSUE TITLE
Is it possible to have the definition file for a formation outside of the sparkleformation directory?

### ISSUE THREAD

**Issue by russellseymour** [sparkleformation/sparkle_formation#182]
Currently I have this structure for my SparkleFormation:

```
.
├── Gemfile
├── Gemfile.lock
├── README.md
├── jenkins.json
└── sparkleformation
    ├── components
    │   └── base.rb
    ├── dynamics
    │   ├── chef_extension.rb
    │   ├── publicip_address.rb
    │   ├── storageAccount.rb
    │   └── ubuntu.rb
    ├── jenkins.rb
    └── registry
        ├── storageaccountname_default.rb
        ├── vmsize.rb
        └── vmsize_default.rb
```

The `jenkins.rb` file in the `sparkleformation` directory is what generates the Azure RM template `jenkins.json`.

I would like to be able have the definition file for generating the template in the root of the repo, at the same level as the resultant template file.  This is so that I can have a library of things to use in a definition but they are not store with the library - that way I can distribute the library to other people to generate templates.

I have tried to move it and run the `sfn` command but I get errors similar to the following:

![image](https://cloud.githubusercontent.com/assets/791658/16146275/207a5e7a-3475-11e6-989a-1bef0e8a3990.png)

Although the file exists at the specified location `sfn` states it does not.  I suspect that this down to the convention of where files should be.

Can this be done?

**Comment by chrisroberts** [comment]
Hi! I believe I understand what you are trying to accomplish, so I'm going to answer based on my assumption. If my assumption is incorrect, please let me know!

You have a collection of files in your `./sparkleformation` directory, and you want other things (projects/repos) to be able to use those files. What you would want in this case is a SparklePack. The packs allow for distribution of files either for direct use, or to build against.

So the first thing would be to create a pack with your core files.

* http://www.sparkleformation.io/docs/sparkle_formation/sparkle-packs.html#distribution

Then, in your other project where you are defining the jenkins template, include your pack within the bundle, and enable it within your `.sfn` file.

* http://www.sparkleformation.io/docs/sfn/sparkle-packs.html#enabling-sparklepacks

And in this new project directory where the jenkins template is defined, if the `./sparkleformtion` directory does not exist, it will load files from `./` and will discover the jenkins template. If you do have a `./sparkleformation` directory and still want the templates to be at root level of the project, you can modify what directory is used for discovery in your `.sfn` file:

```ruby
Configuration.new do
  ...
  base_directory './'
end
```

Let me know if that helps!

**Comment by russellseymour** [comment]
@chrisroberts You have understood it perfectly.

Thanks for this.  I will have a play around and see if I can get it all to work.  I will let you know.

**Comment by russellseymour** [comment]
@chrisroberts I have played around with this and I think I am almost there, but I have a slight issue. 

I have created a SparklePack called `chef-pack` and have generated a `gemspec` for it.  In my project directory for templates I have the following Gemfile:

```ruby
source 'https://rubygems.org'

gem 'sfn'

group :sfn do
  gem 'chef-pack', :path => '../packs/chef-pack'
end
```

I have also updated my `.sfn` file:

```ruby
Configuration.new do

  apply_nesting 'deep'
  processing true


  sparkle_pack [
    'chef-pack'
  ]

  base_directory './'
end
```

And finally I have the following template for `jenkins.rb`:

```ruby
require "chef-pack"

SparkleFormation.new(:compute, :provider => :azure).load(:base).overrides do

  dynamic!(:ubuntu,
           :jenkins,
           {
             :datadisksize => 40,
             :publicip => true,
             :adminpassword => "A96REykZdqWEAJ4H",
           }
          )

end
```

However when I run this with the command `sfn print --file jenkins.rb` I get the following error:

![image](https://cloud.githubusercontent.com/assets/791658/16335090/b80167c0-39fc-11e6-9eb9-23420814c126.png)

I have also tried `bundle exec sfn print --file jenkins.rb` but that does not work either.

I have also removed the `sparkleformation` from the project directory that was created as part of `sfn init`.

I am not sure if the error is from `sfn` or it cannot use my SparklePack for some reason, but I would have thought that would have given a different error.

**Comment by chrisroberts** [comment]
Hi! First, you can remove the `require "chef-pack"` from the template. `sfn` handles all the pack related things during setup. Second, while it's not required, you probably want your template name to match your file name: `SparkleFormation.new(:jenkins, ...)`. It's not required but it does make it easier for tracking.

My assumption is that the template file is not located within the `./test` directory, and when provided a path (relative or absolute), the path will be expanded and then searched. I would recommend hopping up a directory so you are in the root of the project, and then run the command. You can also just reference the template by name, instead of path. Given your current example above, this means you could run:

```bash
$ sfn print --file compute
```

or, if the template is renamed to be `:jenkins`, you could run:

```bash
$ sfn print --file jenkins
```

Let me know if that gets you sorted. Cheers!

**Comment by russellseymour** [comment]
@chrisroberts Thanks that has made things a little better.  

I have removed the `require "chef-pack"` and I take on your point about naming the template appropriately.

I moved up a directory as suggested and now I get a different error:

```
ERROR: NameError: uninitialized constant SparkleFormation::Sparkle::EvalWrapper::SparkleFormation::SparklePack
Did you mean?  SparkleFormation::SparklePack
```

The only place that I have reference to SparklePack is in my `chef-pack.rb` file.  To make this easier my repo for this is at https://github.com/russellseymour/sparkles.

I really appreciate your continued help on this.

**Comment by chrisroberts** [comment]
Hi! I cloned out your repository to try and reproduce what you are experiencing. I see the `./test` directory has a bundle defined with the pack included, and a `.sfn` configuration file which loads the pack. So I run:

```
spox at mothership in ~/P/r/s/test (master|✔)
» be sfn print --file jenkins
ERROR: SparkleFormation::Error::NotFound::Template: Failed to locate item named: `jenkins`
```

Looking at the `.sfn` file, it seems as though the provider isn't set to azure (it defaults to aws), so add that in:

```ruby
Configuration.new do
  #   Set style of stack nesting
  apply_nesting 'deep'
  #   Enable processing of SparkleFormation templates
  processing true

  sparkle_pack [
    'chef-pack'
  ]

  base_directory './'
  credentials.provider :azure
end
```

Running the original command again:

```
spox at mothership in ~/P/r/s/test (master|✚1)
» be sfn print --file jenkins
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
  ...
```

I'm not seeing the `EvalWrapper` related error you're describing in the last comment. My guess is you're running from a different directory? Are you attempting to run from within the `./test` directory?

**Comment by russellseymour** [comment]
@chrisroberts That works - thanks very much.

I was trying to run the `jenkins` template from the root of the repo and not within the test directory.

Thanks again you have been very helpful on this :-).
