### ISSUE TITLE
Specifying registry path, but SparkleFormation not reading files in path

### ISSUE THREAD

**Issue by nothsa** [sparkleformation/sparkle_formation#184]
When attempting to compile my sparkle, I get the following error
```
Failed to locate item named: `testregistry` (SparkleFormation::Error::NotFound::Registry)
```
Obviously this means that it can't find the registry that I'm referencing in my sparkle, but the registry file is definitely in the folder that I specify.

I have the following 3 files to test this setup

```ruby
[registry/testregistry.rb]

SparkleFormation::Registry.register( :testregistry ) do
end
```
```ruby
[templates/testsparkle.rb]

SparkleFormation.new( 'Test-Sparkle' ) do
  registry!( :testregistry )
end
```
```ruby
[compile_sparkle.rb]

require 'sparkle_formation'
SparkleFormation.sparkle_path( '/full/path/to/templates' )
SparkleFormation.registry_path( '/full/path/to/registry' )
SparkleFormation.compile( '/full/path/to/templates/testsparkle.rb' )
```

If I copy `testsparkle.rb` into the `templates` folder and change nothing else, it works. This makes me think that it's ignoring the registry path that I specify.

Any help/insight would be much appreciated.

**Comment by chrisroberts** [comment]
Hi! Responded in IRC but wanted to update the issue as well. Just set the path and then compile:

```ruby
require 'sparkle_formation'
SparkleFormation.sparkle_path('/full/path/to')
SparkleFormation.compile('/full/path/to/templates/testsparkle.rb')
```
and that should get things straight. If you have any problems, please just re-open this issue.

Cheers!
