### ISSUE TITLE
detail-type [''] Syntax error

### ISSUE THREAD

**Issue by phoppe93** [sparkleformation/sparkle_formation#187]
Hi SparkleFormation Team,

i got a syntax error when i try to interprate the following:

event_pattern do
                source ['aws.ec2']
                detail-type ['EC2 Instance State-change Notification']
                detail do
                  state ['terminated']
                end
    end

templates/chef_cleanup_lambda.rb:101: syntax error, unexpected [, expecting keyword_do or '{' or '(' (SyntaxError)
                detail-type ['EC2 Instance State-change Notification']

And i need this json output:

"EventPattern": {
      "source": [
        "aws.ec2"
      ],
      "detail-type": [
        "EC2 Instance State-change Notification"
      ],
      "detail": {
        "state": [
          "stopping"
        ]
      }
    },

**Comment by timurb** [comment]
You can't use dashed keywords as method calls.
Use `event_pattern('detail-type') [...]` or I think otherwise `set!('detail-type) [...]` can be used too (never tried that myself).

**Comment by phoppe93** [comment]
its not working in a array. some other ideas ?

**Comment by chrisroberts** [comment]
Hi @phoppe93. So given the code you started out with:

```ruby
event_pattern do
  source ['aws.ec2']
  detail-type ['EC2 Instance State-change Notification']
  detail do
    state ['terminated']
  end
end
```

The problem is going to be the `detail-type` as it's not valid Ruby syntax for a name (variable, method, etc). You can get around this by doing:

```ruby
event_pattern do
  source ['aws.ec2']
  set!('detail-type', ['EC2 Instance State-change Notification'])
  detail do
    state ['terminated']
  end
end
```

If you are still having problems, please feel free to re-open this issue.

Cheers!
