### ISSUE TITLE
join! does not allow seperator

### ISSUE THREAD

**Issue by runningman84** [sparkleformation/sparkle_formation#188]
Sometimes you want to join array elements with a comma seperator. This does not seem to be possible using the join! function. The seperator is always ''.

**Comment by chrisroberts** [comment]
Hi!

You can provide the delimiter via the options hash in the arguments:

```ruby
join!('thing1', 'thing2', :options => {:delimiter => ','})
```

If you have any problems please feel free to re-open this issue.

Cheers!

**Comment by runningman84** [comment]
thanks, I have not found that in the official docs....

**Comment by chrisroberts** [comment]
Ah, looks like I need to push out an update on the API docs. The applicable spot is here:

http://sparkleformation.github.io/sparkle_formation/SparkleFormation/SparkleAttribute/Aws.html#_cf_join-instance_method

but doesn't include the docs update that got done not too long ago. I'll get it pushed out in a bit. Thanks for pointing that out! :)
