### ISSUE TITLE
map! question

### ISSUE THREAD

**Issue by ianrossi** [sparkleformation/sparkle_formation#19]
@luckymike: @spox I'm having an issue with `map!`. I may be missing something. There's a gist below, but to sum up, I've tried

```map!(:key_map, :global, :key_name)```

(according to the docs) and 

```map!(:key_map, 'global', :key_name)```

 to pull in and assign a value to the launch config resource's `key_name` and either way I get:
 
```json
"KeyName": {
  "Fn::FindInMap": [
    "KeyMap",
    {
      "Ref": "Global"
    },
    "KeyName"
  ]
},
``` 
for the value, and it dies because it's reffing a `Global` resource that doesn't exist. 

Why is the `map!` function turning the map key into a `Ref`?

Here's a full Gist: https://gist.github.com/ianrossi/d3eb20cf6f1743136344

**Comment by chrisroberts** [comment]
This update was _finally_ released in 0.3.0 (https://github.com/sparkleformation/sparkle_formation/tree/v0.3.0)
