### ISSUE TITLE
do not preload .rb files in lib ... or preload them before everything else

### ISSUE THREAD

**Issue by grosser** [sparkleformation/sparkle_formation#195]
got some nasty errors because we load lib/x.rb in one of our templates and then sparkle loads it again

lib/sparkle_formation/sparkle.rb:340

**Comment by grosser** [comment]
... ideally make it so that only dynamics etc 'parts' are preloaded and not templates
... or make `Dir.glob(File.join(root, '**', '**', '*.{json,rb}'))` into a method I can override easily to do what I want ...

**Comment by grosser** [comment]
@chrisroberts 

next issue is our print/validate etc steps taking long because we spend ~30% of the whole execution time loading templates we don't need ...

can you merge https://github.com/sparkleformation/sparkle_formation/pull/196 which fixes it by allowing us to override the lookup pattern

**Comment by grosser** [comment]
ideally logic should be `load these components/dynamics etc` + `load -f file`

**Comment by chrisroberts** [comment]
The loading implementation is what allows layering and inheritance to work. Preventing loading will result in undefined behavior.

With regards to direct loading of a lib and having it loaded again, that can be prevented by moving the `load` within the block. That will allow it to be registered (without loading the lib) and will result in the lib being loaded only if the content block it is within is actually required.

If you are doing loads and requires outside the blocks of the things you are defining (templates, dynamics, etc) then I'm guessing that is what is causing the long startup.

**Comment by grosser** [comment]
how would a lib with "load within the block" look ?
... define a bogus resource ?
but then it would not be loaded at all ...
... not a big deal ... just sad that all this extra work is wasted ...
(loading the file / registering etc when it's not needed ... but also no
idea how to make layering work without loading everything ... )

**Comment by chrisroberts** [comment]
How does the load look right now, and what is its purpose?

Overall, the extra loading should be negligible unless actual work is being done when the files are loaded.

**Comment by grosser** [comment]
libs:
adding monkey-patches and doing 1-time checks ... so having these not loaded at all would be nice since I can handle them with normal requires

other templates:
moving the requires into the blocks already helped a lot ... still a bunch of time wasted ... but not important

before: 1.6s

<img width="1059" alt="screen shot 2016-11-15 at 9 51 26 pm" src="https://cloud.githubusercontent.com/assets/11367/20336284/d2ba53a4-ab7d-11e6-842a-77207bc0307a.png">

with only the template that is needed: 1.4s
<img width="1059" alt="screen shot 2016-11-15 at 9 51 19 pm" src="https://cloud.githubusercontent.com/assets/11367/20336289/d8ed5334-ab7d-11e6-8e3a-0ec2ebca5c44.png">

**Comment by chrisroberts** [comment]
What does the directory structure look like in the project. All the SparkleFormation files should be isolated within a subdirectory for loading (generally is `sparkleformation`, but can be others or configured via `.sfn`). It sounds like it's just loading from project root.

**Comment by grosser** [comment]
yes, everything is in the root ... but the Dir.glob is **/** ... so it does not really matter where it loads from ...
the whole project is "sparkleformation" basically ... so we did not add another level of nesting

**Comment by chrisroberts** [comment]
Sure, the whole project may be "sparkleformation", but it's not composed of _only_ sparkleformation build blocks. That's the reason for the container directory, isolating the building blocks from other code. If you have a `./lib` directory that is doing other things, that flags the need for having a subdirectory to store the building blocks.

**Comment by chrisroberts** [comment]
Closing this as issue can be resolved with updated project layout.
