### ISSUE TITLE
Clarify how to share references between dynamics

### ISSUE THREAD

**Issue by mikelorant** [sparkleformation/sparkle_formation#204]
It is not clear how you would share the references of a dynamic in another dynamic.

Example:

**RDS**
```
dynamic!(:database, :test)
```
Which has an RDS instance with a security group.

**EC2**
```
dynamic!(:my_instance, :test, rds_security_group: [SG OUTPUT FROM RDS STACK])
```

How would you implement this? This is quite relevant when having separate RDS and EC2 sparkle packs. I effectively need a way to ask for the security group from the test database dynamic. Preferably I would like to approach this from the Ruby perspective and write the following (obviously this is not valid):

```
result = dynamic!(:database, :test)
puts! result.security_group
```

Otherwise I'd like to do:
 ```
dynamic!(:my_instance, :test,
  security_group: lookup!(:database, :test, :security_group)
)
```

**Comment by slyness** [comment]
Are you trying to share that resource between two separate stacks? Or are those two distinct dynamics used to create the same stack. I would recommend the later. Either way you have options.

If you are creating a template and including the two dynamics, one to create the RDS instance and one to create an ec2 instance to communicate to the RDS, all of those resources are available to everything in the template. This is even if they are created by two distinct dynamics.

Example
dynamic database.rb creates a security group

```
dynamic!(:ec2_security_group, :test) do
  properties do
    group_description "My security group is so secure"
    vpc_id ref!(:my_vpc_id)
  end
end
```

You now have a resource:

In Json

```
"TestEc2SecurityGroup" {
  "Type": "AWS::EC2::SecurityGroup",
  "Properties": {
    "GroupDescription": "My security group is so secure",
    "VpcId": {
      "Ref": "VpcId"
    }
  }
}
```

and reference:

```
ref!(:test_ec2_security_group)
```

There is nothing keeping you from directly referencing that in your next dynamic included in the template.

So inside the my_instance.rb you can refer to `ref!(:test_ec2_security_group)` or if you felt like passing it to the dynamic more explicitly you could do so in the template at the point where you call the second dynamic

```
dynamic!(:database, :test)

dynamic!(:my_instance, :test,
      :security_group => ref!(:test_ec2_security_group))
```

I would also point out that it might be better practice to have a unique security group either created in the template that calls each dynamic and attach it to the instances or have the my_instance dynamic create the security group and then used as the security group for the RDS database access. 

Alternatively, If you're creating two separate distinct stacks and you expect the security group to be created in one and then be consumed by the RDS stack then you would need to create an output from the first stack and consume it using a parameter in the second stack.

First stack:
Does stuff, Creates Security group, Outputs result

```
dynamic!(:ec2_security_group, :test) do
  properties do
    group_description "My security group is so secure"
    vpc_id ref!(:my_vpc_id)
  end
end

outputs do
  my_security_group.value ref!(:test_ec2_security_group)
end
```

New stack

```
parameters(:my_security_group) do
  type 'String'
end

dynamic!(:my_instance, :test,
        :security_group => ref!(:my_security_group))
```

This creates a complex multiple stack dependency.. and I would suggest is less than I deal in this use case.

I hope this helps.

**Comment by jamesla** [comment]
@slyness Thanks for this write up it's really helpful. In the example where you are passing a value from one dynamic to another dynamic via a template could you explain how I can access the value at the other side?

I have tried via parameters but since they can't accept objects and I haven't yet worked out how to inspect the object I am passing I am finding it very difficult to pass something like an "ec2_subnet"'s id

**Comment by axozoid** [comment]
@jamesla have you managed to figure out how to access values created by dynamics?
I know that one may use `ref!(my_vpc_endpoint.resource_name!)` to refer to the VPC endpoint resource name, but how do I refer to `DnsEntries` and underlying elements (`HostedZoneId` and `DnsName`) ?

**Comment by slyness** [comment]
`attr!(:my_lb_elastic_load_balancing_v2_load_balancer, 'DNSName')`
`attr!(:my_lb_elastic_load_balancing_v2_load_balancer, 'LoadBalancerFullName')`

etcetera...
all Resources that have Return Values will be accessible like this.
