### ISSUE TITLE
AWS sub! should allow single argument

### ISSUE THREAD

**Issue by jqr** [sparkleformation/sparkle_formation#222]
It looks like the AWS `sub!` helper should support being called with just a single parameter (no map) when substituting just template parameters as the real `!Sub` function supports this.

```ruby
sub!("region is ${AWS::Region}")        # errors due to 2 args required
# => !Sub "region is ${AWS::Region}"    # intended working output
```

From [!Sub documentation](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html)
> If you're substituting only template parameters, resource logical IDs, or resource attributes in the String parameter, don't specify a variable map.

I'm using a simple work-around for the moment:
```ruby
sub!("region is ${AWS::Region}", not: "used")
# => !Sub ["region is ${AWS::Region}", {"Not": "used"}]
```

**Comment by jqr** [comment]
Awesome! Thanks @chrisroberts.

**Comment by devkid** [comment]
Hm, still doesn't work for me. I get the following error message:

```
ERROR: Miasma::Error::OrchestrationError::InvalidTemplate: Template error: One or more Fn::Sub intrinsic functions don't specify expected arguments. Specify a string as first argument, and an optional second argument to specify a mapping of values to replace in the string
```

The reason is that the following:
```ruby
sub!('abc')
```

produces the following:
```json
{
    "Fn::Sub": [
        "abc"
    ]
}
```

but should produce the following:
```json
{
    "Fn::Sub": "abc"
}
```
