### ISSUE TITLE
taggable? not working

### ISSUE THREAD

**Issue by markus7811** [sparkleformation/sparkle_formation#225]
it seams as if taggable? is not working:

`dynamic!(:ec2_instance, :testinstance) do 
   properties do 
     dynamic!(:seec_base_tags) if taggable? 
end 
end`

is not working - (without taggable it works...)

error:

`ERROR: NoMethodError: undefined method ``lookup' for #<SparkleFormation:0x00000002342c20> /home/markus/.rvm/gems/ruby-2.1.10/gems/sparkle_formation-3.0.22/lib/sparkle_formation/sparkle_attribute/aws.rb:332:in ``taggable?' /home/markus/.rvm/gems/ruby-2.1.10/gems/sparkle_formation-3.0.22/lib/sparkle_formation/sparkle_attribute/aws.rb:336:in ``taggable?'`

**Comment by chrisroberts** [comment]
Fixed in the latest release. Thanks for the report!
