### ISSUE TITLE
warning: constant ::Fixnum is deprecated...

### ISSUE THREAD

**Issue by fforloff** [sparkleformation/sparkle_formation#232]
When using sparkle_formation gem version 3.0.24 with Ruby 2.4.1 I am getting the following warnings:
vint@belka ~/code/sfn-lab » sfn print --file ecs_infra
/usr/lib/ruby/gems/2.4.0/gems/sparkle_formation-3.0.24/lib/sparkle_formation/sparkle.rb:114: warning: constant ::Fixnum is deprecated
/usr/lib/ruby/gems/2.4.0/gems/sparkle_formation-3.0.24/lib/sparkle_formation/sparkle.rb:114: warning: constant ::Bignum is deprecated
/usr/lib/ruby/gems/2.4.0/gems/sparkle_formation-3.0.24/lib/sparkle_formation/sparkle.rb:114: warning: constant ::NIL is deprecated
/usr/lib/ruby/gems/2.4.0/gems/sparkle_formation-3.0.24/lib/sparkle_formation/sparkle.rb:114: warning: constant ::TRUE is deprecated
/usr/lib/ruby/gems/2.4.0/gems/sparkle_formation-3.0.24/lib/sparkle_formation/sparkle.rb:114: warning: constant ::FALSE is deprecated

Please advise.

**Comment by jimcroft** [comment]
Safe to ignore those warning. The fix has already been merged into the develop branch #228. You can either use that branch or sit tight and wait for the next release.

**Comment by fforloff** [comment]
No worries. Thanks Jim. BTW, I took liberty to create a whalebrew package for the sparkleformation -  https://github.com/whalebrew/whalebrew-packages/pull/51. Will update to alpine:latest once you nave the new release.
