### ISSUE TITLE
sfn doesn't work with cn-north-1 (Bejing AWS region)

### ISSUE THREAD

**Issue by downsj2** [sparkleformation/sparkle_formation#237]
When attempting to use AWS_REGION cn-north-1, sfn fails with:

ERROR: HTTP::ConnectionError: failed to connect: getaddrinfo: nodename nor servname provided, or not known

as it is attempting to use the (non-existent) endpoint cloudformation.cn-north-1.amazonaws.com rather than the correct host cloudformation.cn-north-1.amazonaws.com.cn.

**Comment by chrisroberts** [comment]
Hi there. The configuration can be updated to use the desired host by setting the `api_endpoint` attribute in the credentials block:

```ruby
Configuration.new do
  ...
  credentials do
    ...
    api_endpoint 'amazonaws.com.cn'
  end
end
```

Cheers!
