### ISSUE TITLE
resource description (lib/sparkle_formation/resources/aws_resources.json)

### ISSUE THREAD

**Issue by MikailBag** [sparkleformation/sparkle_formation#238]
1) Where did you get it from?
2) May I use it for my needs?

**Comment by jimcroft** [comment]
@MikailBag I _think_ that file is derived from the public resource specifications available [here](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html).

**Comment by MikailBag** [comment]
Thank you for link to official typings!
