### ISSUE TITLE
for loop issue

### ISSUE THREAD

**Issue by bsushant-athena** [sparkleformation/sparkle_formation#243]
Hi, in this below sparkle-formation code I'm facing an issue where it fails with `ERROR: NoMethodError: undefined method` -' for {"Fn::If"=>["IsDevEnv", 1, 3]}:Hash`
```
_temp_service_count = if!(:is_dev_env, 1, 3)
    for i in 0..(_temp_service_count - 1) do
```
can somebody help me with this?

**Comment by devkid** [comment]
Please reformat your code and error message in a readable manner, post more code (whole template if possible) run `sfn` with `--debug` or set the environment variable `DEBUG=1` to get the full stack trace.

**Comment by bsushant-athena** [comment]
`SparkleFormation.new(:TIMMY_bhai, :provider => :aws) do

	parameters(:environment_name) do
        type 'String'
        allowed_values array!('dev','dev-HA','int','int-HA','prod')
        default 'dev'
    end


	conditions do
        # this means that if EnvironmentName == dev than is_dev_env is true
        is_dev_env equals!(ref!(:environment_name), 'dev')
        # this means that if EnvironmentName == int than is_int_env is true
        is_int_env equals!(ref!(:environment_name), 'int')
	end

	# ======== momo ========

    _momo_service_count = if!(:is_dev_env, 1, 3)

    # now we use ruby to check true or false and set value accordingly
    # this does not work
    #if is_dev_env || is_int_env
    #  _momo_service_count = 1
    #else
    #  _momo_service_count = 3
    #end

	_zones = []
	for i in 0..(_momo_service_count - 1) do
		_zones << "http://momo#{i}-${suffix}.aws.timmy.com/momo/"
	end

end
`

**_# ERROR_**
`[DEBUG]: Initial compile parameters - {}
[DEBUG]: Merged compile parameters - {}
ERROR: NoMethodError: undefined method `-' for {"Fn::If"=>["IsDevEnv", 1, 3]}:Hash
/Users/bsushant/momo/momo-infrastructure/sfn/sparkleformation/timmy_momo.rb:172:in `block in compile'
/Users/bsushant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sparkle_formation-3.0.28/lib/sparkle_formation/sparkle_formation.rb:122:in `instance_exec'
/Users/bsushant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sparkle_formation-3.0.28/lib/sparkle_formation/sparkle_formation.rb:122:in `build'
/Users/bsushant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sparkle_formation-3.0.28/lib/sparkle_formation/sparkle_formation.rb:730:in `block (2 levels) in compile'
/Users/bsushant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sparkle_formation-3.0.28/lib/sparkle_formation/composition.rb:142:in `block in each'
/Users/bsushant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sparkle_formation-3.0.28/lib/sparkle_formation/composition.rb:141:in `each'
/Users/bsushant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sparkle_formation-3.0.28/lib/sparkle_formation/composition.rb:141:in `each'
/Users/bsushant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sparkle_formation-3.0.28/lib/sparkle_formation/sparkle_formation.rb:726:in `block in compile'
/Users/bsushant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bogo-0.2.10/lib/bogo/memoization.rb:64:in `memoize'
/Users/bsushant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sparkle_formation-3.0.28/lib/sparkle_formation/sparkle_formation.rb:697:in `compile'
/Users/bsushant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sparkle_formation-3.0.28/lib/sparkle_formation/sparkle_formation.rb:803:in `nested?'
/Users/bsushant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sfn-3.0.30/lib/sfn/command_module/template.rb:229:in `load_template_file'
/Users/bsushant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sfn-3.0.30/lib/sfn/command/lint.rb:14:in `execute!'
/Users/bsushant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sfn-3.0.30/bin/sfn:52:in `block (4 levels) in <top (required)>'
/Users/bsushant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bogo-cli-0.2.12/lib/bogo-cli/setup.rb:26:in `block in bogo_cli_run'
/Users/bsushant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
/Users/bsushant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
/Users/bsushant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
/Users/bsushant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/slop-3.6.0/lib/slop.rb:54:in `parse'
/Users/bsushant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bogo-cli-0.2.12/lib/bogo-cli/setup.rb:48:in `define'
/Users/bsushant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sfn-3.0.30/bin/sfn:14:in `<top (required)>'
/Users/bsushant/.rbenv/versions/2.5.0/bin/sfn:23:in `load'
/Users/bsushant/.rbenv/versions/2.5.0/bin/sfn:23:in `<main>'`

**Comment by jimcroft** [comment]
The issue here is you're mixing template compile time Ruby code with CloudFormation JSON code / intrinsic functions.

For example. When you compile the template (via sfn print/create/etc) the following line of syntactically correct Ruby code

```
_momo_service_count = if!(:is_dev_env, 1, 3)
```

is evaluated into something like the following:

```
_momo_service_count = {"Fn::If"=>["IsDevEnv", 1, 3]}
```

which is a Ruby hash representation of the CF `Fn:If` function and arguments. When the loop is executed:

```
for i in 0..(_momo_service_count - 1) do
```

that means

```
for i in 0..( {"Fn::If"=>["IsDevEnv", 1, 3]} - 1) do
```

which makes no sense you can't create a range to iterate over between 0 and `Hash`.

There are different ways (and opinions on the best way) to accomplish what you want to do here but I'd probably use a SparkleFormation compile time parameter (http://www.sparkleformation.io/docs/sparkle_formation/compile-time-parameters.html):

eg.
```
SparkleFormation.new(:TIMMY_bhai, :provider => :aws, :compile_time_parameters => {
    :momo_service_count => {
      :type => :number,
      :default => 1
    }
  }
) do

  _zones = []
  for i in 0..(state!(:momo_service_count) - 1) do
    _zones << "http://momo#{i}-${suffix}.aws.timmy.com/momo/"
  end
end
```

This might not be the best solution but hopefully helps illustrate the difference between compile time Ruby code and CloudFormation "code"-like intrinsic functions.

**Comment by bsushant-athena** [comment]
THANKS for the suggestions!! 

_**If I use something like this then what can be the issues?**_

`conditions do
    # this means that if EnvironmentName == dev than is_dev_env is true
    is_dev_env equals!(ref!(:environment_name), 'dev')
    # this means that if EnvironmentName == int than is_int_env is true
    is_int_env equals!(ref!(:environment_name), 'int')
    is_prod equals!(ref!(:environment_name), 'prod')
end

if is_dev_env || is_int_env
  _momo_service_count = 1
end
if is_prod
  _momo_service_count = 3
end

_zones = []
for i in 0..(_momo_service_count - 1) do
	_zones << "http://momo#{i}-${suffix}.aws.timmy.com/momo/"
end`

**Comment by devkid** [comment]
You can add a compile time parameter for the environment name and use this to decide. You can access compile time parameters with `state!(:name)`. So in this case, you could add
```ruby
SparkleFormation.new(:TIMMY_bhai, :provider => :aws, :compile_time_parameters => {
    :environment_name => {
      :type => :string,
      :default => 'dev'
    }
  }
)
```

and then do

```ruby
_momo_service_count = case state!(:environment_name)
                      when 'dev', 'int'
                        1
                      when 'prod'
                        3
                      end
```

**Comment by bsushant-athena** [comment]
Excellent works, but again this compile time variable is not accessible inside resource block.
I'm getting error as below,

```
ERROR: Miasma::Error::ApiError::RequestError: Bad Request - ValidationError: Template format error: Unresolved resource dependencies [EnvironmentName] in the Resources block of the template
```

**Comment by devkid** [comment]
This error indicates that you still have `ref!(:environment_name)` somewhere in your code instead of `state!(:environment_name)`.

When you work on the templates, I suggest to always use `sfn print` to see what certain changes in Ruby do to the generated CloudFormation template.

**Comment by bsushant-athena** [comment]
Yes found the issue, working fine!!
One more thing , do you have a documentation? ...like for most of these answers I could not find any documentation.

**Comment by bsushant-athena** [comment]
hey, but will this work when I add this to aws service catalog?

**Comment by bsushant-athena** [comment]
hey, this thing does not work with AWS Service Catalog ???

**Comment by bsushant-athena** [comment]
so do you know any other way to achieve this?

**Comment by devkid** [comment]
Achieve what? Make it work with Service Catalog? You can generate a CloudFormation template with `sfn print`, pipe it to a file and use that with Service Catalog.

**Comment by jimcroft** [comment]
Your example is extreamly unclear, and lacks a concrete example of what you're actually trying to accomplish.

I'm guessing you're trying to define a number of CloudFormation resources. The number of which depends on the template parameter `environment_name`.

If you can't use sfn in your deployment pipeline and need to use a single pre-compiled/rendered JSON CloudFormation template for use in Service Catalog then your options are limited. The CloudFormation "language" doesn't support loops and it's other programing language like features eg. intrisic functions are very simplisting and limited.

But depending on what you're actually trying to do, as I said, this is still unclear, there might be a way. This is an illustration of how you would launch a stack that contains 1 EC2 instance in a dev environment but say 5 in a production environment. I'm using `AWS::EC2::Instance` resources as an example only, same idea applies to any resource type. I've also ommitted the EC2 properties needed to launch an instance as their irrelevent to this illustration. 

```
SparkleFormation.new(:my_example) do
  parameters do
    environment do
      type 'String'
      default 'dev'
      allowed_values ['dev', 'prod']
    end
  end

  conditions do
    is_prod equals!(ref!(:environment), 'prod')
  end

  5.times do |i|
    resources("instance_#{i}".to_sym) do
      type 'AWS::EC2::Instance'
  
      if i > 0
        on_condition! :is_prod
      end

      properties do
        image_id 'ami-aabbccdd'
        # etc...
      end
    end
  end
end
```

This compiles to the following JSON template.

```
{
  "Parameters": {
    "Environment": {
      "Type": "String",
      "Default": "dev",
      "AllowedValues": [
        "dev",
        "prod"
      ]
    }
  },
  "Conditions": {
    "IsProd": {
      "Fn::Equals": [
        {
          "Ref": "Environment"
        },
        "prod"
      ]
    }
  },
  "Resources": {
    "Instance0": {
      "Type": "AWS::EC2::Instance",
      "Properties": {
        "ImageId": "ami-aabbccdd"
      }
    },
    "Instance1": {
      "Type": "AWS::EC2::Instance",
      "Properties": {
        "ImageId": "ami-aabbccdd"
      }
    },
    "Instance2": {
      "Type": "AWS::EC2::Instance",
      "Condition": "IsProd",
      "Properties": {
        "ImageId": "ami-aabbccdd"
      }
    },
    "Instance3": {
      "Type": "AWS::EC2::Instance",
      "Condition": "IsProd",
      "Properties": {
        "ImageId": "ami-aabbccdd"
      }
    },
    "Instance4": {
      "Type": "AWS::EC2::Instance",
      "Condition": "IsProd",
      "Properties": {
        "ImageId": "ami-aabbccdd"
      }
    }
  }
}
```

Where ths first instance is always provisioned but the others are only provisioned if you set environment to be prod. This is basic CloudFormation and doesn't rely on any SparkleFormation specific functionality.

Hope that helps.

**Comment by chrisroberts** [comment]
@jimcroft 's example is exactly what you want to accomplish the behavior you are looking for using only cloudformation functionality. 

Closing this issue as it can be considered resolved. Cheers!
