### ISSUE TITLE
/var/lib/gems/2.3.0/gems/attribute_struct-0.4.2/lib/attribute_struct/monkey_camels.rb:37:in `camel_to_s': stack level too deep (SystemStackError)

### ISSUE THREAD

**Issue by moatazelmasry2** [sparkleformation/sparkle_formation#244]
Hi there,

i'm trying to create my first sparkleformation stack, and getting the following error:

```
/var/lib/gems/2.3.0/gems/attribute_struct-0.4.2/lib/attribute_struct/monkey_camels.rb:37:in `camel_to_s': stack level too deep (SystemStackError)
	from /var/lib/gems/2.3.0/gems/hashie-3.5.7/lib/hashie/extensions/indifferent_access.rb:71:in `convert_key'
	from /var/lib/gems/2.3.0/gems/hashie-3.5.7/lib/hashie/extensions/indifferent_access.rb:107:in `indifferent_writer'
	from /var/lib/gems/2.3.0/gems/hashie-3.5.7/lib/hashie/extensions/coercion.rb:44:in `set_value_with_coercion'
	from /var/lib/gems/2.3.0/gems/bogo-0.2.12/lib/bogo/smash.rb:172:in `block (2 levels) in to_type_converter'
	from /var/lib/gems/2.3.0/gems/bogo-0.2.12/lib/bogo/smash.rb:166:in `each'
	from /var/lib/gems/2.3.0/gems/bogo-0.2.12/lib/bogo/smash.rb:166:in `block in to_type_converter'
	from /var/lib/gems/2.3.0/gems/bogo-0.2.12/lib/bogo/smash.rb:158:in `tap'
	from /var/lib/gems/2.3.0/gems/bogo-0.2.12/lib/bogo/smash.rb:158:in `to_type_converter'
	 ... 9073 levels...
	from /var/lib/gems/2.3.0/gems/bogo-cli-0.2.12/lib/bogo-cli/setup.rb:48:in `define'
	from /var/lib/gems/2.3.0/gems/sfn-3.0.30/bin/sfn:14:in `<top (required)>'
	from /usr/local/bin/sfn:22:in `load'
	from /usr/local/bin/sfn:22:in `<main>'
``` 

Here's are the versions of the listed packages:

```
ruby 2.3
bogo (0.2.12)
bogo-cli (0.2.12)
hashie (3.5.7)
sfn (3.0.30)
```

I'm able to run `sfn print --file abc` successfully and creating a cloudformation stack based on the output of this command.

Any idea what is happening?

**Comment by chrisroberts** [comment]
Hi. What command are you running that causes the error? Can you please run that command with the `--debug` flag and paste in the full output. If the error occurs with a specific template, please also include that template if possible.

Thanks!

**Comment by moatazelmasry2** [comment]
Hi there, just tried this again today and surprisingly everything worked!!!. Maybe it was some network/proxy problems on our corporate side. 

Thanks for your quick reply. Closing

**Comment by devkid** [comment]
The error you posted is definitely not network related. This seems to happen if you refer to a section that you are in the process of defining, e.g. something like that:
```ruby
some_hash do
  root!.some_hash do
    # ...
  end
end
```

**Comment by moatazelmasry2** [comment]
Ah I see. Indeed I was working on a similar snippet. This might be as well be the error. what's nerving about this issue, is that there are no way  for a user to know at what part of the code, this error is happening
