### ISSUE TITLE
Not able to get value but getting reference

### ISSUE THREAD

**Issue by bsushant-athena** [sparkleformation/sparkle_formation#247]
Hi, In my usecase I've some parameters which user provides and then accordingly I've to decide whether to choose A or B.
But when I'm accessing this A or B I get reference instead of value.
```
conditions do
    is_small_gw                equals!(ref!(:gateway_mode), 'small')
  end

  gwn_mem_usage = if!(
    :is_small_gw,
    1.4,
    5.5
  )

```
And in other file I need to access that variable.

```
files('/etc/prometheus/prometheus.rules') do
    context do
      GWN_MEM_USAGE               ref!(:gwn_mem_usage)
    end
    content join!(
       File.read('sparkleformation/files/prometheus/b.rules'),
       a_rules
    )
  end
```
The error I get is 
```
ERROR: Miasma::Error::ApiError::RequestError: Bad Request - ValidationError: Template format error: Unresolved resource dependencies [GwnMemUsage] in the Resources block of the template
```
So how can I access this variable inside the context as a value?

**Comment by chrisroberts** [comment]
Hi there. In this case you are just using a defined variable to set the value, not referencing a resource within the template, so using `ref!` is not required. You can just do:

```
GWN_MEM_USAGE gwn_mem_usage
```

Cheers!

**Comment by bsushant-athena** [comment]
@chrisroberts I already did that but I'm still not getting the value.
When I tried puts!(gwn_mem_usage) ..I  get empty response
