### ISSUE TITLE
Oversized sparkleformation template error

### ISSUE THREAD

**Issue by bsushant-athena** [sparkleformation/sparkle_formation#255]
Hi Team,

I'm getting below error from my sparkleformation code 
`templateBody' failed to satisfy constraint: Member must have length less than or equal to 51200`

Can someone please suggest how to avoid this?

Thanks,
Sushant

**Comment by webframp** [comment]
You can workaround this error by ensuring the template is uploaded to an s3 bucket first. @chrisroberts can confirm for sure, but I think there is an `--upload-root-template` option.

**Comment by chrisroberts** [comment]
Hi there. @webframp is correct, you will need to define a bucket to store templates in your configuration and use the `--upload-root-template` option. Templates that are sent directly within the request have a smaller size limitation imposed on them, which you are hitting.

Cheers!
