### ISSUE TITLE
Azure helper resource_id! is not idempotent

### ISSUE THREAD

**Issue by redterror** [sparkleformation/sparkle_formation#268]
Hi, I am working on a codebase originally built on sparkleformation 3.0.24 and we have code that programmatically builds up Azure resources with blocks such as this:

```
  default_routing_table_resource = dynamic!(:network_route_tables, parameters!(:default_routing_table_name), :resource_name_suffix => "") do
    location resource_group!().location.to_s
    api_version '2016-03-30'
  end
  subnets = {
    "GatewaySubnet"       => {prefix: :gateway_subnet_address_prefixes},
    "dmz-subnet-01"       => {prefix: :dmz_subnet_01_address_prefixes, nsg: "dmz", route_tbl: default_routing_table_resource},
    "public-subnet-01"    => {prefix: :public_subnet_01_address_prefixes, nsg: "default", route_tbl: default_routing_table_resource, service_endpoints: svc_endpoints},
  }

  compiled_subnets = subnets.collect do |(subname, subdef)|
    array!(->{
      name subname
      properties.address_prefix parameters!(subdef[:prefix]).to_s
      if subdef[:nsg]
        properties.network_security_group.id resource_id!(sg_resources[subdef[:nsg]].resource_name!).to_s
      end
      if subdef[:route_tbl]
        properties.route_table.id resource_id!(subdef[:route_tbl].resource_name!).to_s
      end
      if subdef[:service_endpoints]
        properties.service_endpoints subdef[:service_endpoints].collect{|svc| {service: svc} }
      end
    })
  end.reduce(&:+)
```

What we have observed is that the calls in the `subnets.collect` block work successfully on the first iteration, but fail on the second iteration.  Specifically, the call on this line:

```
      if subdef[:route_tbl]
        properties.route_table.id resource_id!(subdef[:route_tbl].resource_name!).to_s
      end
```

On the first iteration through the loop, `subdef[:route_tbl].resource_name!` returns the correct thing.  Somehow the `resource_id` call alters the return value of `subdef[:route_tbl].resource_name!` such that on the second iteration, `resource_name!` returns the result of `resource_id!(subdef[:route_tbl].resource_name!).to_s`, yielding in effect `resource_id!(resource_id!(...))` which of course fails.

Reverting 655b63 fixes the issue.  Are we doing something wrong in our calls or is this a legitimate bug?

PS - I recognize this would benefit substantially from an example, but I wanted to write this up since I hit this issue ~2 years ago and pinned our project to 3.0.24.  I'd like to be able to stay current.

**Comment by chrisroberts** [comment]
Hi! I've been running some tests and everything seems to behaving as expected. I have added a test that describes what you were doing and the behavior seen from the tests is what is expected. If you still see the same error please do let me know what I can change about the test to generate the same type of failure you are experiencing. Thanks!
