### ISSUE TITLE
How is the Condition Being Used?

### ISSUE THREAD

**Issue by yhuang** [sparkleformation/sparkle_formation#32]
https://github.com/sparkleformation/sparkle_formation/blob/master/lib/sparkle_formation/sparkle_attribute.rb#L160

I don't see how the condition is being written.  I only see the true outcome and the false outcome generated.

**Comment by chrisroberts** [comment]
Can you provide an example of what you currently have, and the output it generates?

**Comment by yhuang** [comment]
This is what I would like to do.  I want to define conditions (which is not working either):

  conditions.use_db_snapshot do
    not!(
      equals!(
      	"",
        ref!(:snapshot_id)
      )
    )
  end

and reference it:

db_name if!(
        :use_db_snapshot,
        ref!("AWS::NoValue"),
        ref!("DbName")
      )

Here is the output I get empty conditions and no condition reference:

  "Conditions": {
    "UseDbSnapshot": {
    }
  },

"DbName": {
          "Fn::If": [
            {
              "Ref": "AWS::NoValue"
            },
            {
              "Ref": "DbName"
            }
          ]
        },

**Comment by chrisroberts** [comment]
Hi! Okay, so the issue here is that the helper methods being used are generating values. Thinking of it in terms of a hash might be useful. The condition helper methods are used for values only. In your example above, the `not!` is being used as a key, which results in nothing being added to the resulting hash. The fix to get what you're looking for should be:

```ruby
conditions do
  use_db_snapshot not!(equals!("", ref!(:snapshot_id)))
end
```

Give that a try and see if it gets you what you're expecting. If you are still having issues, please let me know. Cheers!

**Comment by yhuang** [comment]
Hi chrisroberts,

Thank you for responding so quickly!  Ok, so the conditions section is now generating output I had expected:

  "Conditions": {
    "UseDbSnapshot": {
      "Fn::Not": [
        {
          "Fn::Equals": [
            "",
            {
              "Ref": "SnapshotId"
            }
          ]
        }
      ]
    }
  }

How should I fix my reference to the condition so it would render correctly?

      db_name if!(
        :use_db_snapshot,
        ref!("AWS::NoValue"),
        ref!("DbName")
      )

produces:

        "DbName": {
          "Fn::If": [
            {
              "Ref": "AWS::NoValue"
            },
            {
              "Ref": "DbName"
            }
          ]
        }

which is not referencing the condition I just defined.  Thank you again for your help.

**Comment by chrisroberts** [comment]
Hi! This is a bug. The reformatted argument wasn't being injected into the array. I have a fix in the `develop` branch currently. I'll get a release cut either later this evening, or in the morning tomorrow. If you use a bundle you can point at the develop branch until then. Thanks!

**Comment by yhuang** [comment]
I will happily wait for patch to be merged and released.  Thank you for producing a fix so quickly.

**Comment by chrisroberts** [comment]
@yhuang Sorry for the delay. This fix has been released:

https://github.com/sparkleformation/sparkle_formation/tree/v0.2.8

Thanks for the report!
