### ISSUE TITLE
Generated JSON Output Issue with FN::IF

### ISSUE THREAD

**Issue by yhuang** [sparkleformation/sparkle_formation#35]
SparkFormation:

      db_name if!(
        :use_db_snapshot,
        ref!("AWS::NoValue"),
        ref!("DbName")
      )
...
  conditions do
    use_db_snapshot not!(
      equals!(
        "",
        ref!(:snapshot_id)
      )
    )
  end

JSON:

        "DbName": {
          "Fn::If": [
            {
              "Condition": "UseDbSnapshot"
            },
            {
              "Ref": "AWS::NoValue"
            },
            {
              "Ref": "DbName"
            }
          ]
        }
...
  "Conditions": {
    "UseDbSnapshot": {
      "Fn::Not": [
        {
          "Fn::Equals": [
            "",
            {
              "Ref": "SnapshotId"
            }
          ]
        }
      ]
    }
  }

===

I expected the generated JSON to be like this:

        "DBSnapshotIdentifier": {
          "Fn::If": [
            "UseDbSnapshot",
            {
              "Ref": "SnapshotId"
            },
            {
              "Ref": "AWS::NoValue"
            }
          ]
        }

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-conditions.html#d0e43197

**Comment by chrisroberts** [comment]
Hi! This was simply me mis-reading the documentation. I have applied an update to properly generate the name instead of the condition structure. The fix is available in the latest release (v0.2.10). Thanks for reporting this bug!
