### ISSUE TITLE
Everything gets capitalized by SparkleFormation::Utils::AnimalCase's camel method

### ISSUE THREAD

**Issue by gswallow** [sparkleformation/sparkle_formation#37]
In the docs, there are examples of components like this:

  mappings.ami_to_region do
    set!('us-east-1', :ami => 'ami-xxxxxx')
    set!('us-west-2', :ami => 'ami-xxxxxx')
  end

This generates invalid cfn templates as the U gets capitalized

This works fine:

  mappings.ami_to_region do
    _camel_keys_set(:auto_disable)
    set!('us-east-1', :ami => 'ami-xxxxxx')
    set!('us-west-2', :ami => 'ami-xxxxxx')
  end

Is that the design?

Thanks.

**Comment by luckymike** [comment]
Yes. You can also use the `_no_hump` method on an individual string, if you like:

```
set!('us-east-1'._no_hump, :ami => 'ami-xxxxxx')
```

**Comment by luckymike** [comment]
We'll update the docs! Thanks for catching this.

**Comment by gswallow** [comment]
I like .no_hump.  It's simple :)

Conversely, I have to specify some strings like this:
  parameters(:chef_server_u_r_l) do

Is there a better way to create "ChefServerURL" in the resulting json than what I'm doing?

**Comment by chrisroberts** [comment]
Since types matter, you can use that to your advantage here:

```ruby
parameters('ChefServerURL') do
  ...
end
```
