### ISSUE TITLE
Conditionals and Sparkleformation don't mix

### ISSUE THREAD

**Issue by gswallow** [sparkleformation/sparkle_formation#40]
Hi,

I've used conditionals in my cfn templates in the past, and I'm learning that with this tool, conditionals are bad.

Consider an EBS volume.  With traditional cfn templates, I would set up a conditional, go through the AWS rigamarole of comparing the "volume type" parameter with "io1" and then either refer to the "piops" parameter or refer to the 'AWS::NoValue' parameter.  Is this the recommended practice?

I ask because the conditionals have static names, but let's say I want to spin up two EC2 instances; one with an io2 EBS volume and another with a gp2 EBS volume?  The same conditional would be created, twice, with different results.

Thanks again!

**Comment by luckymike** [comment]
Hey! I'm not clear about why you couldn't continue to do that with your :sparkles:? Are you running into problems with it, or just asking about whether SparkleFormation offers a different/better pattern?

**Comment by gswallow** [comment]
I'm asking if SparkleFormation recommends a better pattern.  The only difference between the EBS volume dynamics is the inclusion of a "piops" property.  IIRC Cloudformation will actually blow chunks if you try to include the "piops" property on a "gp2" volume.  Therefore, I'm just creating two dynamics: one for gp2/magnetic, and one for io1.

Is using ruby, or creating more dynamics, the better way?

**Comment by gswallow** [comment]
Hrm.  Perhaps I found my answer, partially, in:

https://gist.github.com/gswallow/48e32e0c27c2e8f7ea64

**Comment by luckymike** [comment]
Oh,  excellent! Here are four ways to address it, all good SparkleFormation patterns. Which you choose will depend on your use case.

Suppose this is your EBS dynamic:

```ruby
SparkleFormation.dynamic(:ebs_volume) do |_name, _config={}|
  resources("#{_name}_ebs_vol".to_sym) do 
    type 'AWS::EC2::Volume'  
    properties do 
      availability_zone ref!(:az)
      size ref!(:ebs_size)
      volume_type ref!(:ebs_type)
    end
  end
end
```
You could:

#### Override via your template
If you always use IOPS for a specific service, and never use it for others, and each service has its own SparkleFormation template, you can add the IOPS bits in the template like so:
```ruby
dynamic!(:ebs_volume, 'app')

resources.app_ebs_vol do
  properties do
    volume_type 'io1'
    iops ref!(:ebs_iops_size)
  end
end
```

#### IOPS Dynamic
If you have multiple templates where you would always like to use IOPS, but others where you don't, you can add an IOPS dynamic that inserts the ebs volume dynamic then provides the overrides:
```ruby
SparkleFormation.dynamic(:ebs_iops) do |_name, _config={}|
  dynamic!(:ebs_volume, _name)
  
  resources("#{_name}_ebs_vol".to_sym) do
    properties do
      volume_type 'io1'
      iops ref!(:ebs_iops_size)
    end
  end
end
```

#### Pass it as config
As your gist shows, you can also pass config to the dynamic that indicates you'd like an IOPS volume. I would do something like this to also make the parameter conditional:
```ruby
SparkleFormation.dynamic(:ebs_volume) do |_name, _config={}|
  resources("#{_name}_ebs_vol".to_sym) do 
    type 'AWS::EC2::Volume'  
    properties do 
      availability_zone ref!(:az)
      size ref!(:ebs_size)
      volume_type ref!(:ebs_type)
    end
  end

  if _config(:iops) 
    parameters(:ebs_iops_size) do
      type 'String'
    end

    resources("#{_name}_ebs_vol".to_sym) do
      properties do
        volume_type 'io1'
        iops ref!(:ebs_iops_size)
      end
    end
  end

end
```

#### ENV Variable
Finally, if you need this to be configurable at run time (which your current AWS Conditional method is), you can drive the ruby conditional via your ENV.
```ruby
SparkleFormation.dynamic(:ebs_volume) do |_name, _config={}|
  resources("#{_name}_ebs_vol".to_sym) do 
    type 'AWS::EC2::Volume'  
    properties do 
      availability_zone ref!(:az)
      size ref!(:ebs_size)
      volume_type ref!(:ebs_type)
    end
  end

  if ENV['iops']
    parameters(:ebs_iops_size) do
      type 'String'
    end

    resources("#{_name}_ebs_vol".to_sym) do
      properties do
        volume_type 'io1'
        iops ref!(:ebs_iops_size)
      end
    end
  end

end
```
Which allows you to provision with IOPS by prepending your create command like this (assuming you provision using a CLI tool):
`iops=true bundle exec knife cloudformation create...`

**Comment by luckymike** [comment]
In terms of recommended practice, the AWS Conditionals are still really useful, but I think in this case handling it with one of the above methods is preferable. The unused iops parameter is potentially confusing and it feels like this is a design decision you would probably make prior to writing your template anyway.

**Comment by luckymike** [comment]
One more (coming soon) option: the newly exposed state!() function: https://github.com/sparkleformation/sparkle_formation/issues/36#issuecomment-71085443

**Comment by gswallow** [comment]
This does what I want (handed to me by @djtreder):

SparkleFormation.dynamic(:ebs_volume) do |_name, _config = { :snapshot_id => 'none' }|
   instance_eval(
  "conditionals do
    #{_config[:snapshot_id].gsub('-','_')}_is_none equals!(_config[:snapshot_id], 'none')
  end"
  )
end

**Comment by luckymike** [comment]
:+1:

**Comment by chrisroberts** [comment]
Hi! Just a couple things to add. First, you shouldn't ever need to do an `instance_eval`. Helpers are around to prevent needing that sort of thing in general, and I have yet to find myself in a situation requiring that as a solution. For what you provided above, you could get the same behavior using:

```ruby
conditions.set!(
  "#{_config[:snapshot_id].gsub('-', '')}_is_none".to_sym, 
  equals!(_config[:snapshot_id], 'none')
)
```
Something else you can consider is that the iops property supports the "no value", and you could thus create the conditional to use template references to provide the proper result, allowing parameter updates outside the template generation to properly reconfigure the volume. That would look something like:

```ruby
conditions.set!(
  "#{_name}_ebs_iops".to_sym,
  equals!(ref!("#{_name}_ebs_volume_type".to_sym), 'io1')
)
...
resources("#{_name}_ebs_volume".to_sym) do
  type 'AWS::EC2::Volume'
  properties do
    availability_zone attr!(_config[:instance], :availability_zone)
    volume_type ref!("#{_name}_ebs_volume_type".to_sym)
    snapshot_id ref!("#{_name}_ebs_snapshot_id".to_sym)
    iops if!(
      condition!("#{_name}_ebs_iops".to_sym),
      ref!("#{_name}_ebs_provisioned_iops".to_sym),
      no_value!
    )
    size ref!("#{_name}_ebs_volume_size".to_sym)
  end
end
```

That should make things a little cleaner in the dynamic, and it has the added benefit of the condition being built using the value provided to the stack via the parameter which makes it updateable without a template update.

(also, just a warning, I haven't run the stuff above, just typed it out as I was going, so hopefully there's no typos!)

Cheers!
