### ISSUE TITLE
Add support for layered `Sparkle`s

### ISSUE THREAD

**Issue by chrisroberts** [sparkleformation/sparkle_formation#46]
Now that we can isolate parts within a `Sparkle`, allow `SparkleFormation` instance to contain a stack of `Sparkle` containers which it can pull from. This will allow the pathway for distributed sfn parts (community sparkles) \o/

**Comment by ianrossi** [comment]
Love it

**Comment by chrisroberts** [comment]
Implemented. Needs usage coverage in spec with multiple sparkles loaded to validate expected precedence.

**Comment by chrisroberts** [comment]
implemented
