### ISSUE TITLE
Issue when using AWS SDK for Ruby

### ISSUE THREAD

**Issue by techshell** [sparkleformation/sparkle_formation#49]
When trying to get a list of AWS availability zones within a region to pre-populate some parameters in my sfn template, I get an `uninitialized constant SparkleFormation::Aws::EC2 (NameError)` error when I use the AWS SDK. When debugging you see something along the lines of:

```
.rvm/gems/ruby-2.1.2@sfn-templates/gems/attribute_struct-0.2.8/lib/attribute_struct/monkey_camels.rb:39: warning: instance variable @__not_camel not initialized
```
The sfn template looks something like this:

```ruby
require 'aws-sdk'

ec2 = Aws::EC2::Client.new
azs = ec2.describe_availability_zones.availability_zones.map(&:zone_name)

SparkleFormation.new(:create_vpc_with_subnets).load(:base, :vpc).overrides do
#<snip>
```

Note, if I use Fog ... everything is fine, despite it looking very similar and with Camel Case  `ec2 = Fog::Compute.new(params)`

Thoughts?

**Comment by luckymike** [comment]
Can you share an example of how you use the `azs` variable in your template?

Side note, this is a clever idea, so I'd love to see it work (and to borrow it)!

**Comment by hatimabdalla** [comment]
I'm trying to replicate what @gswallow is doing in [cfn-templates](https://github.com/gswallow/cfn-templates/blob/master/vpc/cloudformation/templates/vpc.rb) , see line 70. He create a public and a private subnet in each AZ within a region:
```ruby
  azs.each do |az|
    dynamic!(:subnet, "public_#{az}", :az => az, :type => :public)
    public_subnets << "public_#{az}_subnet".gsub('-','_').to_sym
    dynamic!(:subnet, "private_#{az}", :az => az, :type => :private)
  end
```
My current templates use the intrinsic function `get_azs!())` , but that presents particular challenges with us-east-1 region.

**Comment by luckymike** [comment]
Hey @hatimabdalla,

I'm not terribly familiar with the aws-sdk, but I took a few stabs in the dark, and got this to work. Here's my revised code:
```
require 'aws-sdk'

ec2 = AWS::EC2::Client.new
azs = ec2.describe_availability_zones[:availability_zone_info].collect { |z| z[:zone_name] }
```
The upcased `AWS::EC2` is weird, since the aws-sdk docs pretty plainly show `Aws::EC2`, but I got it to work in both SparkleFormation and irb with `AWS`, and it failed both places with `Aws`. `availability_zones` does not appear to be a method, but once irb showed me the values for ec2.describe_availability_zones, I just @gswallow's code to what aws-sdk gave.

Thanks for the exercise; I really dig this approach to handling subnets!

**Comment by techshell** [comment]
Hi @luckymike ,

Not sure how you managed to get this working, for me aws-sdk doesn't work with upcased AWS::EC2, see:
```shell
$ irb                                                                                                                                                                                               
2.1.2 :001 > require 'aws-sdk'
 => true
2.1.2 :002 > ec2 = AWS::EC2::Client.new
NameError: uninitialized constant AWS
	from (irb):2
	from /Users/hatim/.rvm/rubies/ruby-2.1.2/bin/irb:11:in `<main>'
2.1.2 :003 >
```

**Comment by luckymike** [comment]
```
michael@luckymike ~ $ irb
2.1.1-gems :001 > require 'aws-sdk'
 => true 
2.1.1-gems :002 > ec2 = AWS::EC2::Client.new
 => #<AWS::EC2::Client::V20141001> 
```
michael@luckymike ~ $ gem list | grep aws-sdk
aws-sdk (1.63.0)
aws-sdk-v1 (1.63.0)
```

**Comment by techshell** [comment]
Ahh, you are using a very old version of the sdk, http://aws.amazon.com/sdk-for-ruby/

```shell
$ gem list | grep aws-sdk
aws-sdk (2.0.48)
aws-sdk-core (2.0.48)
aws-sdk-resources (2.0.48)
```

**Comment by luckymike** [comment]
Ahh, I see the same issue with the newer gem. I wonder if this is a namespacing issue somewhere.

Here's a not too pretty, but not too ugly workaround, SparkleFormation configs are Ruby (whether it's a `.knife.rb` with knife-cloudformation, or `.sfn` bogo file), so I did the following in my config:

```
require 'aws-sdk'
ec2 = Aws::EC2::Client.new
ENV['azs'] = ec2.describe_availability_zones.availability_zones.map(&:zone_name).join(',')
```
Then in my template:
```
azs = ENV.fetch('azs').split(',')
```
Handling this in the config alongside AWS keys and region actually feels kind of right, though the conversion from string to array and back is obviously not the best way to go. I'm sure there's a better way to handle that, but this works for Saturday morning!

**Comment by JonathanSerafini** [comment]
Yeah ... Aws is a class that's defined within SparkleFormation, which is the same namespace the file/block gets evaluated to, so that's the top most object you're getting. What you want to do instead is call Aws from the global namespace, prefixing Aws with ::
```
require 'aws-sdk-core'
ec2 = ::Aws::EC2::Client.new
azs = ec2.describe_availability_zones.availability_zones.map(&:zone_name)
```

**Comment by chrisroberts** [comment]
This looks resolved. Please open a new issue if required.
