### ISSUE TITLE
_no_hump and _camel_keys_set(:_disable) ignored in Mappings hash keys

### ISSUE THREAD

**Issue by btisdall** [sparkleformation/sparkle_formation#50]
Hi and thanks for bringing much needed sanity to CloudFormation. I've got a problem using a mapping to look up something based on some parameter and some other arbitrary key (in the case a lower-cased environment name), viz:

```
SparkleFormation.build do
  mappings.sns_topic_url do
    _set('us-east-1'._no_hump, 'test'._no_hump => 'arn:aws:sns:XXXXXXXX'), 'production'._no_hump => 'arn:aws:sns:YYYYYYYY')
  end
end
```
Despite my calling `_no_hump` on the bottom level keys the rendered mapping has, for example, "Test", thus the template is invalid. Am I being daft or missing a better approach?

Thanks.

**Comment by chrisroberts** [comment]
Hi! This looks like an issue with how the `Hash` type value is being processed (and probably duped which Ruby does automatically with `String` keys and thus loses some context). However, you _can_ easily get around that by using block syntax instead. If you update your component to look like this:

```ruby
SparkleFormation.build do
  mappings.sns_topic_url do
    set!('us-east-1'._no_hump) do
      set!('test'._no_hump, 'arn:aws:sns:XXXXXXXX')
      set!('production'._no_hump, 'arn:aws:sns:YYYYYYYY')
    end
  end
end
```

you should be all set! I'll also see about adding in an explicit check for `Hash` type values and force customized duping to pull context along with it.

**Comment by btisdall** [comment]
Brilliant, thanks for the amazingly speedy response Chris!

**Comment by matschaffer** [comment]
Also bumped into this last week. Glad there's a work around. Might be nice to get the "humping" semantics into the docs.

**Comment by chrisroberts** [comment]
Hi! I was actually messing around with the functionality this weekend within the underlying library to allow for sparkleformation to "do the right thing" with `Hash` type setting (which goes a little beyond retention of key styling). The next release will be doing the right thing. Also, the docs have been getting an overhaul (in the `develop` branch) and will be updated once this next release ships.

**Comment by chrisroberts** [comment]
This is fixed for the pending release (!) so closing this up.
