### ISSUE TITLE
Add output helper

### ISSUE THREAD

**Issue by chrisroberts** [sparkleformation/sparkle_formation#52]
Add `output!` helper to provide auto formatting when referencing outputs from stack type resources

**Comment by chrisroberts** [comment]
this is a great idea!

**Comment by luckymike** [comment]
If I understand your note-to-self correctly, this IS a great idea!

**Comment by chrisroberts** [comment]
all about past me looking out for future me

**Comment by chrisroberts** [comment]
Using `stack_output!` name to prevent confusion

**Comment by chrisroberts** [comment]
implemented, closing.
