### ISSUE TITLE
correct syntax for weirdly cased resource properties?

### ISSUE THREAD

**Issue by psi** [sparkleformation/sparkle_formation#53]
Hello! I'm taking a stab at bringing up an RDS instance with SparkleFormation and ran into an issue with SparkleFormation's camel-casing of properties not matching up with what Amazon is expecting in all cases. I started out expecting this to work:

```ruby
resources.main_db do
  type 'AWS::RDS::DBInstance'
  properties do
    engine 'MySQL'
    engine_version '5.6'
    allocated_storage 100
    multi_az true
    db_instance_class 'db.m1.small'
    storage_type 'io1'
    iops 1000
    master_username 'root'
    master_user_password '$3kr37pw'
  end
end
```

But, I quickly figured out that 'multi_az' was getting translated to 'MultiAz' rather than 'MultiAZ' and that 'db_instance_class' was being translated to 'DbInstanceClass' instead of 'DBInstanceClass'. I figured out two possible workarounds. The first was to change the property names to 'multi_a_z' and 'd_b_instance_class' to trick the camel casing, but that's obviously on the wrong side of elegance ;)

What I settled on was this:

```ruby
resources.main_db do
  type 'AWS::RDS::DBInstance'
  properties do
    engine 'MySQL'
    engine_version '5.6'
    allocated_storage 100
    storage_type 'io1'
    iops 1000
    master_username 'root'
    master_user_password '$3kr37pw'

    set!('MultiAZ'._no_hump, true)
    set!('DBInstanceClass'._no_hump, 'db.m1.small')
   end
end
```

I'm happy enough with that syntax, I just wanted to check that I'm using the correct/recommended syntax.  It wasn't immediately obvious to me that `set!` would work in that context from the docs, so assuming this is the right way to do things, I'd be happy to create a PR adding an example.

Thanks for your help and for SparkleFormation!

JD

**Comment by chrisroberts** [comment]
Hi! That's likely the most direct way, though you shouldn't need the `._no_hump` when setting:

```ruby
    set!('MultiAZ', true)
    set!('DBInstanceClass', 'db.m1.small')
```
should be sufficient. The camel casing is tricky with situations like this, and using the `#set!` was my compromise so I wouldn't be trying to chase down an implementation that would always produce the "correct" conversion.

And always happy for PRs! Cheers!

**Comment by psi** [comment]
Good deal. Thanks!

**Comment by cornelf** [comment]
how about multi_a_z?
