### ISSUE TITLE
Allow importing 

### ISSUE THREAD

**Issue by rabidscorpio** [sparkleformation/sparkle_formation#54]
No one seems to have asked anything about how to handle user_data for a launchconfig so maybe I'm missing something, is there a way to take an erb template or a shell script and add it to the user_data for a launchconfig with sparkle_formation encoding and interpolating it? Or even just pointing to a file that already has text base64 encoded?

Everything I've seen shows base64 encoded text directly in the template (which defeats the whole point of using sparkle_formation in the first place) instead of included from another file.

**Comment by chrisroberts** [comment]
Hi! There is no builtin support for this type of behavior, and it's not something that I would want to add directly into the library itself (for a variety of reasons). I generally treat user_data as a way to start execution of something, not as the entirety of the thing to execute. In practice this means that the user_data consists of just enough setup to get cfn-init started, with all the actual commands I want run or contents of scripts defined within the `AWS::CloudFormation::Init`.

Since the templates are just Ruby, you can easily add support for any way you would like to pull in that content. If you have a file on your local system you would like to use, you can do something like:

```ruby
user_data base64!(::File.read('/my/script'))
```

You could also provide yourself ERB support doing the same sort of thing as above, but loading the erb library and calling out to it. The library itself isn't placing any constraints on _how_ the data is provided. The only important thing to remember is that you'll need to force the root namespace to access the constants (like the `::File` above). 

Hope that helps. If you have any other questions, please ask. 

Cheers!

**Comment by runningman84** [comment]
How would you import stuff like this?

```
"AWS::CloudFormation::Init": {
          "configSets": {
            "InstallAndRun": [
              "install_cfn",
              "install_chef",
              "configure_chef",
              "run_chef"
            ]
          },
          "upgrade_system": {
            "commands": {
              "01_apt_get_update": {
                "command": "apt-get update -qq"
              },
              "02_apt_get_upgrade": {
                "command": "apt-get upgrade -qq"
              }
            }
          },
          "install_cfn": {
            "files": {
              "/etc/cfn/cfn-hup.conf": {
                "content": {
                  "Fn::Join": [
                    "", [
                      "[main]\n",
                      "stack=", {
                        "Ref": "AWS::StackId"
                      },
                      "\n",
                      "region=", {
                        "Ref": "AWS::Region"
                      },
                      "\n"
                    ]
                  ]
                },
                "mode": "000400",
                "owner": "root",
                "group": "root"
              },
              "/etc/cfn/hooks.d/cfn-auto-reloader.conf": {
                "content": {
                  "Fn::Join": [
                    "", [
                      "[cfn-auto-reloader-hook]\n",
                      "triggers=post.update\n",
                      "path=Resources.SensuInstance.Metadata.AWS::CloudFormation::Init\n",
                      "action=/opt/aws/bin/cfn-init -v ",
                      "         --stack ", {
                        "Ref": "AWS::StackName"
                      },
                      "         --resource SensuInstance ",
                      "         --configsets InstallAndRun ",
                      "         --region ", {
                        "Ref": "AWS::Region"
                      },
                      "\n"
                    ]
                  ]
                },
                "mode": "000400",
                "owner": "root",
                "group": "root"
              }
            },
```

**Comment by chrisroberts** [comment]
Hi!. Here is an example of a cfn init that should be helpful:

https://github.com/hw-labs/infrastructure-repository/blob/master/cloudformation/registry/chef.rb

**Comment by runningman84** [comment]
That is a greate example! But I have another question, how do I use this one?
https://github.com/hw-labs/infrastructure-repository/blob/master/cloudformation/registry/instance_parameters.rb
If I put it in my dynamic node,
```
SparkleFormation.dynamic(:node) do |_name, _config = {}|

  registry!(:instance_parameters, _name, _config)
```
 the parameters are written below the description which does not make sense:
```
  "Description": "AWS CloudFormation Sample Template ...",
  "GraphiteInstanceSize": {
    "AllowedValues": [
      "t2.micro",
      "t2.small",
      "t2.medium",
      "m3.medium",
      "m3.large",
      "m3.xlarge",
      "m3.2xlarge"
    ],
    "Default": "t2.micro",
    "Description": "Size of created instance",
    "Type": "String"
  },
  "GraphiteInstanceStorageType": {
    "Default": "ssd",
    "AllowedValues": [
      "ssd",
      "io",
      "instance"
    ],
    "Description": "Instance storage type",
    "Type": "String"
  },
  "Resources": {
    "GraphiteNode": {
      "Type": "AWS::EC2::Instance",
      "Properties": {
...
```

**Comment by chrisroberts** [comment]
It just needs to be wrapped within a `parameters do; end` block. You can see an example of it in use here: https://github.com/hw-labs/infrastructure-repository/blob/master/cloudformation/dynamics/node.rb#L3-L13

**Comment by runningman84** [comment]
great that works fine, another question why do you use
```

  dynamic!(:security_group, _name) do
     properties do
       group_description "Instance security group (#{_name})"
       security_group_ingress array!(
         -> {
           ip_protocol 'tcp'
           from_port '22'
           to_port '22'
           cidr_ip '0.0.0.0/0'
         }
       )
     end
   end
```
instead of this in your dynamic node example?
```
   resources("#{_name}_security_group2".to_sym) do
      properties do
        group_description "Instance security group (#{_name})"
        security_group_ingress array!(
          -> {
            ip_protocol 'tcp'
            from_port '22'
            to_port '22'
            cidr_ip '0.0.0.0/0'
          }
        )
      end
    end
```

**Comment by chrisroberts** [comment]
It is using a feature of the `dynamic!` method that provides a skeleton structure for known resource types, which you can read more about in the still-in-progress pull request: https://github.com/sparkleformation/sparkle_formation/blob/update/docs/docs/building-blocks.md#builtin-dynamics

**Comment by runningman84** [comment]
Thanks for your great help! It would be cool if you could update your examples here
https://github.com/sparkleformation/sparkle_formation/tree/master/examples
https://github.com/hw-labs/infrastructure-repository
to the new concepts...

**Comment by chrisroberts** [comment]
Yep, #58 is a documentation overhaul to cover all the features and the functionality of the library itself (including all the new features in the next release). The examples will get an update in that PR as well.

**Comment by chrisroberts** [comment]
Closing this up. Please open a new issue if required.

**Comment by matschaffer** [comment]
Incase anyone ends up here looking for a way to inject ERB-processed user data scripts, I came up with this. Seems to work at first pass but just finished it moments ago:

```rb
require 'erubis'

class SfEruby < Erubis::Eruby
  include Erubis::ArrayEnhancer

  def add_expr(src, code, indicator)
    case indicator
      when '='
        src << " #{@bufvar} << (" << code << ');'
      else
        super
    end
  end
end

SparkleFormation.dynamic(:erb_user_data) do |_name, _config={}|
  template = File.read(File.join(File.dirname(__FILE__), '..', 'templates', _name))
  user_data base64!(join!(SfEruby.new(template).evaluate(self)))
end
```

Once this is loaded you can do `dynamic!(:erb_user_data, 'somefile.sh.erb')` and inside that erb you can use things like `ref!(:environment)` and they still get injected properly. Might be useful for someone so thought I'd post here.
