### ISSUE TITLE
Compress template size

### ISSUE THREAD

**Issue by mg03** [sparkleformation/sparkle_formation#78]
While creating a template the size is coming out to be a tad bit bigger than the 51200 aws limit. Is there a switch or parameter in sparkleformation that will strip of the new line characters and bring the template down in size, so that I dont have to go for nesting.

**Comment by luckymike** [comment]
The newlines are only used in the print view. If you're using `sfn create` the template will be stripped of those characters.

If you have parameter descriptions, you should be able to safely remove them to get your template size down.

**Comment by mg03** [comment]
ah, ok ... thanx
