### ISSUE TITLE
Usage of state! when compiling nested stacks

### ISSUE THREAD

**Issue by nexus49** [sparkleformation/sparkle_formation#81]
I am trying to pass a state hash to all templates that are compiled as part of a deep_nesting compilation, but looking at the source code it seems from my brief understanding that the state is not passed to compile in the case of deep_nesting.

Please let me know if this is possible and i am using it wrong. 

I tested a few variations, but it seems the state is not considered when running:
`sfn = SparkleFormation.compile(templateFile, :sparkle, :state => { :co => configHash })`

and also not as part of the calls to apply_nesting or apply_deep_nesting

Your feedback is appreciated!

**Comment by chrisroberts** [comment]
:+1:

**Comment by chrisroberts** [comment]
Alright, this has been released in the 0.x version and will be ready to roll shortly for 1.0. It's got some new things coming along with it (which require some doc updates) so hoping to have it ready to ship in the next day-ish.

**Comment by nexus49** [comment]
Cool, thanks for the turn around!

**Comment by chrisroberts** [comment]
Hi! This is all fixed up. There's docs covering the usage as well which goes over how things are used when nesting stacks: http://www.sparkleformation.io/docs/sparkle_formation/compile-time-parameters.html

Thanks for the report!
