### ISSUE TITLE
Accessing data 

### ISSUE THREAD

**Issue by mg03** [sparkleformation/sparkle_formation#84]
As per , http://sparkleformation.github.io/sparkle_formation/UserDocs/sparkleformation-dsl.html, Data Access can be done for parameters. 
Is there a way to access data inside a mapping?

**Comment by luckymike** [comment]
@mg03 CFN mappings are in a top-level hash `'Mappings': {}`, so you could access them with the same pattern.

If you just need to reference a mapping entry, use the `map!` helper function (equivalent to Fn::FindInMap), which is documented here: http://www.sparkleformation.io/docs/sparkle_formation/anatomy.html#mappings

**Comment by chrisroberts** [comment]
As @luckymike stated, the same pattern can be used to access mappings or any other structure within template that has been defined at the point of attempting to access. It is important to note that the data returned is merely the value defined within the template at that location as this access is occurring prior to being pushed to an API and evaluated.

**Comment by mg03** [comment]
@luckymike : i kinda figured it would be. Thanx ....
@chrisroberts : thanx for re-emphazising on the data availability being prior to evaluation , what im not clear on is the following: 
Can i call aws and get a value say "x" and then on the basis of that value "x" , evaluate a mapping which has "x" defined in it , have sparklefn create the template and then call stack creation....

Maybe im asking for too much, but if the above is possible or ludicrous, either ways let me know ..

Sorry - to comment on a closed issue, i didnt know if you prefer a new one or not ....
