### ISSUE TITLE
Run Time parameters

### ISSUE THREAD

**Issue by gauravyadav01** [sparkleformation/sparkle_formation#97]
Hi, 

We can easily figure out compile time parameter through parameters struct. 
Is there anything through which I can extract run time parameters ?

I want to implement condition based parameter prompt. 
if an input is provided in run time duration, it will ask or not ask the next parameter on the basis of previous condition.

Thanks

**Comment by chrisroberts** [comment]
Hi! This is not possible. The template is fully generated prior to user prompting via `sfn` and `sfn` works directly from the generated template. It may be worthwhile to have separate templates if they function differently, or refactor how your template is built. Without more context, I can't provide more help than that.
