### ISSUE TITLE
nested objects root! inconsistencies

### ISSUE THREAD

**Issue by JonathanSerafini** [sparkleformation/sparkle_formation#98]
It appears that calling `root!` from deeply nested data structures will generally return `self` rather than the expected root node. Looking at `def root` in attribute_struct would seem to indicate that calling `root` would recursively chaining `parent` objects, however this doesn't seem to be the case. 

For instance, in the following example you'll see that `parent!` returns the previous scope whereas `root!` returns the local scope. 

You can see this in the following example : 

```ruby
template = SparkleFormation.new(tpl_name) do
  # Common header
  #
  set! "AWSTemplateFormatVersion", "2010-09-09"
  description "#{tpl_description}"
  #
  # Template
  #
  dynamic! :lambda_function, :factory do
    properties do
      nest1 do
        root!.nest1_root "nest1"
        parent!.root!.nest1_parent_root "nest1"
        deep1 do
          here "deep1"
          root!.nest1_deep1_root "nest1deep1"
          parent!.nest1_deep1_parent "nest1deep1"
          parent!.root!.nest1_deep1_parent_root "nest1deep1"
          parent!.parent!.parent!.nest1_deep1_parent_parent_parent "nest1deep1"
        end
      end
    end
  end
end
```

```json
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "",
  "Resources": {
    "FactoryLambdaFunction": {
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "Nest1": {
          "Nest1Root": "nest1",
          "Nest1Deep1Root": "nest1deep1",
          "Nest1Deep1Parent": "nest1deep1",
          "Nest1Deep1ParentRoot": "nest1deep1",
          "Deep1": {
            "Here": "deep1"
          }
        }
      },
      "Nest1Deep1ParentParentParent": "nest1deep1"
    }
  },
  "Nest1ParentRoot": "nest1"
}
```

**Comment by chrisroberts** [comment]
Nice catch. Was able to get it reproduced and tracked down to:

https://github.com/chrisroberts/attribute_struct/commit/e66e7f842fa5e0bfa33d44aa97e8b6ee42796118#diff-bc568d63851e5e21538e95b637c1064aR464

Will get a release out shortly to get this resolved.

**Comment by chrisroberts** [comment]
Fix released in v1.1.6. Thanks for the report and the example to reproduce it easily!

**Comment by JonathanSerafini** [comment]
Awesome, thanks as always Chris.

**Comment by calebhailey** [comment]
@JonathanSerafini we would like your input on a new SparkleFormation service. Please contact me at caleb@heavywater.io at your earliest convenience for more information. :smile:
